##**Context**

Developers rely on StackOverflow-style Q&A as a primary source of troubleshooting and implementation guidance, but searching manually can be slow and inconsistent. Even when search results are relevant, developers often have to open multiple links, compare answers, and decide which solution is most trustworthy. This process becomes especially inefficient when questions are time-sensitive, the user is unfamiliar with the topic, or when similar questions exist with slightly different edge cases.

A **Retrieval-Augmented Generation (RAG)** assistant addresses this by combining two strengths:
* **Retrieval:** Find the most relevant historical Q&A threads from a knowledge base quickly and consistently.
* **Generation:** Produce a concise, human-readable response that summarizes the best solution(s) while grounding the answer in retrieved sources.

This project focuses on building a general-purpose StackOverflow RAG assistant—not limited to one domain like pandas—so that the assistant can handle a wide variety of developer questions (Python, SQL, tooling, web development, etc.). Because StackOverflow posts often include code, links, and noisy formatting (HTML), this also introduces realistic challenges: cleaning text, handling short/ambiguous queries, avoiding hallucinations, and controlling context length.

##**Objective**

The goal of this project is to build and evaluate a general StackOverflow RAG assistant that can:
1. **Retrieve relevant sources reliably**
    * Convert Q&A content into embeddings and index them using FAISS for fast similarity search.
    * Improve ranking precision using a cross-encoder reranker to better identify the most relevant answer when queries are short or ambiguous.
2. **Generate concise responses grounded in evidence**
    * Use an instruction-tuned LLM to generate a short bullet-point answer based only on retrieved context.
    * Ensure the output is consistently formatted (3–5 bullets) and avoids irrelevant or invented details.
3. **Increase trust and reduce hallucination risk**
    * Provide source attribution (citations) so users can trace each answer back to retrieved posts.
    * Implement reliability guardrails such as retrieval-score gating, token-budget truncation (to avoid context overflow), and “refuse to answer” behavior when evidence is weak.
4. **Evaluate the system like a production pipeline**
    * Measure retrieval quality using Hit@k under both “full question” and “first sentence” (leakage-reduced) scenarios.
    * Quantify the impact of reranking on Hit@1 (a key driver of RAG quality).
    * Track generation reliability (citation compliance, refusal rate) and latency (retrieval vs reranking vs generation time).

##**Success criteria:**
* Strong retrieval accuracy on leakage-reduced queries (improved Hit@1 after reranking),
* Consistent grounded answers with high citation compliance,
* Reasonable refusal rate for low-evidence queries,
* Measured latency breakdown showing where optimization matters.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import json

notebook_path = "/content/drive/MyDrive/Colab Notebooks/GenAI_StackOverflow_RAG"  # change this

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

nb.get("metadata", {}).pop("widgets", None)

clean_path = "/content/clean_notebook.ipynb"

with open(clean_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Saved cleaned notebook:", clean_path)

**Install relavent packages**

In [ ]:
!pip -q install datasets sentence-transformers faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 41.1 MB/s eta 0:00:00


In [ ]:
!pip -q install -U transformers accelerate bitsandbytes sentence-transformers faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 70.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 11.7 MB/s eta 0:00:00


In [ ]:
!pip -q install --no-cache-dir \
  "transformers==4.46.3" \
  "accelerate==0.34.2" \
  "huggingface_hub==0.36.2" \
  "tokenizers>=0.20,<0.21" \
  "safetensors>=0.4.3"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 73.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 146.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.4/324.4 kB 246.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 217.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 174.1 MB/s eta 0:00:00


**Import Required Libraries**

In [ ]:
import os
import re
import torch
import time
from typing import Set
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from transformers import AutoConfig
from google.colab import userdata
from datasets import load_dataset
from sentence_transformers import SentenceTransformer
from sentence_transformers import CrossEncoder
import numpy as np
import pandas as pd
import faiss
import warnings
warnings.filterwarnings("ignore", category=FutureWarning, module="bitsandbytes")

**Setup Hugging Face Token - for faster downloads**

In [ ]:
os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")
print("HF_TOKEN set:", os.environ["HF_TOKEN"][:8] + "...")

HF_TOKEN set: hf_AKKQA...


**Load a StackOverflow dataset from Hugging Face**

In [ ]:
ds = load_dataset("HuggingFaceH4/stack-exchange-preferences", split="train")
print(ds)
print(ds.features)

README.md: 0.00B [00:00, ?B/s]

Resolving data files:   0%|          | 0/758 [00:00<?, ?it/s]

data/Stackoverflow.com/train-00008-of-00(…):   0%|          | 0.00/48.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00001-of-00(…):   0%|          | 0.00/62.4M [00:00<?, ?B/s]

data/3dprinting.stackexchange.com/train-(…):   0%|          | 0.00/4.66M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00002-of-00(…):   0%|          | 0.00/60.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00006-of-00(…):   0%|          | 0.00/51.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00004-of-00(…):   0%|          | 0.00/53.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00013-of-00(…):   0%|          | 0.00/46.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00010-of-00(…):   0%|          | 0.00/46.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00000-of-00(…):   0%|          | 0.00/77.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00005-of-00(…):   0%|          | 0.00/51.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00012-of-00(…):   0%|          | 0.00/46.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00011-of-00(…):   0%|          | 0.00/45.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00009-of-00(…):   0%|          | 0.00/47.3M [00:00<?, ?B/s]

data/3dprinting.meta.stackexchange.com/t(…):   0%|          | 0.00/191k [00:00<?, ?B/s]

data/Stackoverflow.com/train-00003-of-00(…):   0%|          | 0.00/55.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00007-of-00(…):   0%|          | 0.00/48.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00014-of-00(…):   0%|          | 0.00/45.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00015-of-00(…):   0%|          | 0.00/44.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00016-of-00(…):   0%|          | 0.00/44.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00017-of-00(…):   0%|          | 0.00/44.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00018-of-00(…):   0%|          | 0.00/43.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00019-of-00(…):   0%|          | 0.00/43.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00020-of-00(…):   0%|          | 0.00/42.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00021-of-00(…):   0%|          | 0.00/42.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00022-of-00(…):   0%|          | 0.00/42.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00023-of-00(…):   0%|          | 0.00/42.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00024-of-00(…):   0%|          | 0.00/42.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00025-of-00(…):   0%|          | 0.00/42.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00027-of-00(…):   0%|          | 0.00/41.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00028-of-00(…):   0%|          | 0.00/41.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00026-of-00(…):   0%|          | 0.00/41.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00029-of-00(…):   0%|          | 0.00/41.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00030-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00031-of-00(…):   0%|          | 0.00/41.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00032-of-00(…):   0%|          | 0.00/41.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00033-of-00(…):   0%|          | 0.00/40.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00034-of-00(…):   0%|          | 0.00/40.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00035-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00036-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00037-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00038-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00039-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00040-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00041-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00042-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00043-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00044-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00045-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00046-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00047-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00048-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00050-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00049-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00051-of-00(…):   0%|          | 0.00/39.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00052-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00053-of-00(…):   0%|          | 0.00/39.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00054-of-00(…):   0%|          | 0.00/39.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00055-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00056-of-00(…):   0%|          | 0.00/39.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00057-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00058-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00060-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00059-of-00(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00061-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00062-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00063-of-00(…):   0%|          | 0.00/39.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00064-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00065-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00066-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00068-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00067-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00069-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00070-of-00(…):   0%|          | 0.00/39.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00071-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00072-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00073-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00074-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00075-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00076-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00077-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00078-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00080-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00079-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00081-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00082-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00084-of-00(…):   0%|          | 0.00/39.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00083-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00085-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00086-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00087-of-00(…):   0%|          | 0.00/39.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00090-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00095-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00093-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00089-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00088-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00094-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00092-of-00(…):   0%|          | 0.00/40.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00091-of-00(…):   0%|          | 0.00/41.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00097-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00096-of-00(…):   0%|          | 0.00/39.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00100-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00098-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00099-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00102-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00101-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00103-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00104-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00105-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00106-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00107-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00108-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00109-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00110-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00111-of-00(…):   0%|          | 0.00/39.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00112-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00113-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00114-of-00(…):   0%|          | 0.00/40.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00115-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00117-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00116-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00118-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00119-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00120-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00121-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00122-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00123-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00124-of-00(…):   0%|          | 0.00/39.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00125-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00126-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00127-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00128-of-00(…):   0%|          | 0.00/40.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00129-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00131-of-00(…):   0%|          | 0.00/38.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00130-of-00(…):   0%|          | 0.00/39.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00132-of-00(…):   0%|          | 0.00/38.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00133-of-00(…):   0%|          | 0.00/38.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00134-of-00(…):   0%|          | 0.00/38.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00135-of-00(…):   0%|          | 0.00/38.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00136-of-00(…):   0%|          | 0.00/38.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00137-of-00(…):   0%|          | 0.00/38.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00139-of-00(…):   0%|          | 0.00/38.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00142-of-00(…):   0%|          | 0.00/39.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00144-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00140-of-00(…):   0%|          | 0.00/38.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00143-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00141-of-00(…):   0%|          | 0.00/38.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00138-of-00(…):   0%|          | 0.00/38.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00145-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00146-of-00(…):   0%|          | 0.00/39.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00147-of-00(…):   0%|          | 0.00/39.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00148-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00149-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00150-of-00(…):   0%|          | 0.00/39.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00151-of-00(…):   0%|          | 0.00/39.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00153-of-00(…):   0%|          | 0.00/39.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00152-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00156-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00154-of-00(…):   0%|          | 0.00/39.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00155-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00157-of-00(…):   0%|          | 0.00/38.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00158-of-00(…):   0%|          | 0.00/38.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00159-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00160-of-00(…):   0%|          | 0.00/41.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00161-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00162-of-00(…):   0%|          | 0.00/39.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00163-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00164-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00165-of-00(…):   0%|          | 0.00/39.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00166-of-00(…):   0%|          | 0.00/38.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00167-of-00(…):   0%|          | 0.00/39.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00170-of-00(…):   0%|          | 0.00/40.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00168-of-00(…):   0%|          | 0.00/39.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00169-of-00(…):   0%|          | 0.00/40.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00173-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00171-of-00(…):   0%|          | 0.00/41.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00174-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00172-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00175-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00177-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00176-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00178-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00179-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00180-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00181-of-00(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00182-of-00(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00184-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00183-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00185-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00186-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00187-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00190-of-00(…):   0%|          | 0.00/40.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00194-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00189-of-00(…):   0%|          | 0.00/39.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00193-of-00(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00191-of-00(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00192-of-00(…):   0%|          | 0.00/40.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00188-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00195-of-00(…):   0%|          | 0.00/40.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00196-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00197-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00198-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00200-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00202-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00201-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00199-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00203-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00204-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00205-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00206-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00207-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00208-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00209-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00210-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00211-of-00(…):   0%|          | 0.00/40.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00212-of-00(…):   0%|          | 0.00/40.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00213-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00214-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00218-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00215-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00220-of-00(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00217-of-00(…):   0%|          | 0.00/40.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00216-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00219-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00221-of-00(…):   0%|          | 0.00/41.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00223-of-00(…):   0%|          | 0.00/40.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00222-of-00(…):   0%|          | 0.00/40.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00224-of-00(…):   0%|          | 0.00/40.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00225-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00226-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00227-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00229-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00228-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00231-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00230-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00232-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00233-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00234-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00237-of-00(…):   0%|          | 0.00/40.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00236-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00238-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00239-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00235-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00240-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00241-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00242-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00243-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00245-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00244-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00246-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00247-of-00(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00248-of-00(…):   0%|          | 0.00/41.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00249-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00250-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00251-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00252-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00253-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00254-of-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00255-of-00(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00257-of-00(…):   0%|          | 0.00/40.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00256-of-00(…):   0%|          | 0.00/40.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00258-of-00(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00260-of-00(…):   0%|          | 0.00/40.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00259-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00262-of-00(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00261-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00264-of-00(…):   0%|          | 0.00/40.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00263-of-00(…):   0%|          | 0.00/40.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00265-of-00(…):   0%|          | 0.00/40.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00266-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00267-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00268-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00269-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00270-of-00(…):   0%|          | 0.00/41.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00271-of-00(…):   0%|          | 0.00/41.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00272-of-00(…):   0%|          | 0.00/41.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00273-of-00(…):   0%|          | 0.00/40.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00274-of-00(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00275-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00277-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00276-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00279-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00278-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00280-of-00(…):   0%|          | 0.00/40.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00282-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00281-of-00(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00283-of-00(…):   0%|          | 0.00/40.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00284-of-00(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00285-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00286-of-00(…):   0%|          | 0.00/39.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00287-of-00(…):   0%|          | 0.00/39.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00288-of-00(…):   0%|          | 0.00/39.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00289-of-00(…):   0%|          | 0.00/39.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00290-of-00(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00291-of-00(…):   0%|          | 0.00/41.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00292-of-00(…):   0%|          | 0.00/40.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00293-of-00(…):   0%|          | 0.00/40.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00294-of-00(…):   0%|          | 0.00/39.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00295-of-00(…):   0%|          | 0.00/39.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00296-of-00(…):   0%|          | 0.00/38.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00297-of-00(…):   0%|          | 0.00/38.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00298-of-00(…):   0%|          | 0.00/38.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00299-of-00(…):   0%|          | 0.00/38.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00300-of-00(…):   0%|          | 0.00/38.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00301-of-00(…):   0%|          | 0.00/38.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00302-of-00(…):   0%|          | 0.00/39.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00303-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00304-of-00(…):   0%|          | 0.00/40.1M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00305-of-00(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00306-of-00(…):   0%|          | 0.00/38.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00308-of-00(…):   0%|          | 0.00/38.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00307-of-00(…):   0%|          | 0.00/38.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00309-of-00(…):   0%|          | 0.00/38.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00311-of-00(…):   0%|          | 0.00/38.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00310-of-00(…):   0%|          | 0.00/40.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00316-of-00(…):   0%|          | 0.00/38.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00312-of-00(…):   0%|          | 0.00/38.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00313-of-00(…):   0%|          | 0.00/38.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00315-of-00(…):   0%|          | 0.00/38.0M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00314-of-00(…):   0%|          | 0.00/38.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00317-of-00(…):   0%|          | 0.00/37.8M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00319-of-00(…):   0%|          | 0.00/38.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00318-of-00(…):   0%|          | 0.00/38.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00320-of-00(…):   0%|          | 0.00/38.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00321-of-00(…):   0%|          | 0.00/38.6M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00322-of-00(…):   0%|          | 0.00/38.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00323-of-00(…):   0%|          | 0.00/37.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00325-of-00(…):   0%|          | 0.00/38.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00324-of-00(…):   0%|          | 0.00/39.3M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00326-of-00(…):   0%|          | 0.00/37.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00327-of-00(…):   0%|          | 0.00/37.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00328-of-00(…):   0%|          | 0.00/37.4M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00329-of-00(…):   0%|          | 0.00/37.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00330-of-00(…):   0%|          | 0.00/37.7M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00331-of-00(…):   0%|          | 0.00/36.9M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00332-of-00(…):   0%|          | 0.00/37.2M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00333-of-00(…):   0%|          | 0.00/36.5M [00:00<?, ?B/s]

data/Stackoverflow.com/train-00334-of-00(…):   0%|          | 0.00/35.4M [00:00<?, ?B/s]

data/academia.meta.stackexchange.com/tra(…):   0%|          | 0.00/1.61M [00:00<?, ?B/s]

data/academia.stackexchange.com/train-00(…):   0%|          | 0.00/35.6M [00:00<?, ?B/s]

data/academia.stackexchange.com/train-00(…):   0%|          | 0.00/36.3M [00:00<?, ?B/s]

data/ai.meta.stackexchange.com/train-000(…):   0%|          | 0.00/255k [00:00<?, ?B/s]

data/ai.stackexchange.com/train-00000-of(…):   0%|          | 0.00/5.35M [00:00<?, ?B/s]

data/android.meta.stackexchange.com/trai(…):   0%|          | 0.00/596k [00:00<?, ?B/s]

data/android.stackexchange.com/train-000(…):   0%|          | 0.00/20.5M [00:00<?, ?B/s]

data/anime.meta.stackexchange.com/train-(…):   0%|          | 0.00/1.24M [00:00<?, ?B/s]

data/anime.stackexchange.com/train-00000(…):   0%|          | 0.00/9.12M [00:00<?, ?B/s]

data/apple.meta.stackexchange.com/train-(…):   0%|          | 0.00/979k [00:00<?, ?B/s]

data/apple.stackexchange.com/train-00000(…):   0%|          | 0.00/33.2M [00:00<?, ?B/s]

data/apple.stackexchange.com/train-00001(…):   0%|          | 0.00/33.8M [00:00<?, ?B/s]

data/arduino.meta.stackexchange.com/trai(…):   0%|          | 0.00/311k [00:00<?, ?B/s]

data/askubuntu.com/train-00000-of-00005.(…):   0%|          | 0.00/37.9M [00:00<?, ?B/s]

data/arduino.stackexchange.com/train-000(…):   0%|          | 0.00/16.8M [00:00<?, ?B/s]

data/askubuntu.com/train-00001-of-00005.(…):   0%|          | 0.00/35.2M [00:00<?, ?B/s]

data/askubuntu.com/train-00002-of-00005.(…):   0%|          | 0.00/34.3M [00:00<?, ?B/s]

data/askubuntu.com/train-00003-of-00005.(…):   0%|          | 0.00/37.0M [00:00<?, ?B/s]

data/askubuntu.com/train-00004-of-00005.(…):   0%|          | 0.00/38.2M [00:00<?, ?B/s]

data/astronomy.meta.stackexchange.com/tr(…):   0%|          | 0.00/260k [00:00<?, ?B/s]

data/astronomy.stackexchange.com/train-0(…):   0%|          | 0.00/12.2M [00:00<?, ?B/s]

data/aviation.meta.stackexchange.com/tra(…):   0%|          | 0.00/832k [00:00<?, ?B/s]

data/aviation.stackexchange.com/train-00(…):   0%|          | 0.00/32.9M [00:00<?, ?B/s]

data/avp.stackexchange.com/train-00000-o(…):   0%|          | 0.00/4.06M [00:00<?, ?B/s]

data/avp.meta.stackexchange.com/train-00(…):   0%|          | 0.00/160k [00:00<?, ?B/s]

data/beer.meta.stackexchange.com/train-0(…):   0%|          | 0.00/81.6k [00:00<?, ?B/s]

data/beer.stackexchange.com/train-00000-(…):   0%|          | 0.00/1.38M [00:00<?, ?B/s]

data/bicycles.meta.stackexchange.com/tra(…):   0%|          | 0.00/555k [00:00<?, ?B/s]

data/bicycles.stackexchange.com/train-00(…):   0%|          | 0.00/29.0M [00:00<?, ?B/s]

data/bioinformatics.meta.stackexchange.c(…):   0%|          | 0.00/127k [00:00<?, ?B/s]

data/bioinformatics.stackexchange.com/tr(…):   0%|          | 0.00/3.33M [00:00<?, ?B/s]

data/biology.stackexchange.com/train-000(…):   0%|          | 0.00/16.2M [00:00<?, ?B/s]

data/biology.meta.stackexchange.com/trai(…):   0%|          | 0.00/906k [00:00<?, ?B/s]

data/bitcoin.meta.stackexchange.com/trai(…):   0%|          | 0.00/263k [00:00<?, ?B/s]

data/blender.meta.stackexchange.com/trai(…):   0%|          | 0.00/629k [00:00<?, ?B/s]

data/bitcoin.stackexchange.com/train-000(…):   0%|          | 0.00/15.5M [00:00<?, ?B/s]

data/blender.stackexchange.com/train-000(…):   0%|          | 0.00/25.5M [00:00<?, ?B/s]

data/boardgames.meta.stackexchange.com/t(…):   0%|          | 0.00/726k [00:00<?, ?B/s]

data/boardgames.stackexchange.com/train-(…):   0%|          | 0.00/13.7M [00:00<?, ?B/s]

data/bricks.meta.stackexchange.com/train(…):   0%|          | 0.00/173k [00:00<?, ?B/s]

data/buddhism.stackexchange.com/train-00(…):   0%|          | 0.00/28.8M [00:00<?, ?B/s]

data/bricks.stackexchange.com/train-0000(…):   0%|          | 0.00/2.61M [00:00<?, ?B/s]

data/chess.meta.stackexchange.com/train-(…):   0%|          | 0.00/237k [00:00<?, ?B/s]

data/chemistry.stackexchange.com/train-0(…):   0%|          | 0.00/24.2M [00:00<?, ?B/s]

data/cardano.meta.stackexchange.com/trai(…):   0%|          | 0.00/42.5k [00:00<?, ?B/s]

data/chinese.meta.stackexchange.com/trai(…):   0%|          | 0.00/348k [00:00<?, ?B/s]

data/cardano.stackexchange.com/train-000(…):   0%|          | 0.00/1.18M [00:00<?, ?B/s]

data/chemistry.meta.stackexchange.com/tr(…):   0%|          | 0.00/1.50M [00:00<?, ?B/s]

data/buddhism.meta.stackexchange.com/tra(…):   0%|          | 0.00/786k [00:00<?, ?B/s]

data/chess.stackexchange.com/train-00000(…):   0%|          | 0.00/13.0M [00:00<?, ?B/s]

data/chinese.stackexchange.com/train-000(…):   0%|          | 0.00/13.7M [00:00<?, ?B/s]

data/christianity.meta.stackexchange.com(…):   0%|          | 0.00/2.73M [00:00<?, ?B/s]

data/christianity.stackexchange.com/trai(…):   0%|          | 0.00/50.2M [00:00<?, ?B/s]

data/civicrm.meta.stackexchange.com/trai(…):   0%|          | 0.00/51.1k [00:00<?, ?B/s]

data/codegolf.meta.stackexchange.com/tra(…):   0%|          | 0.00/8.43M [00:00<?, ?B/s]

data/codegolf.stackexchange.com/train-00(…):   0%|          | 0.00/31.9M [00:00<?, ?B/s]

data/civicrm.stackexchange.com/train-000(…):   0%|          | 0.00/5.19M [00:00<?, ?B/s]

data/codegolf.stackexchange.com/train-00(…):   0%|          | 0.00/48.0M [00:00<?, ?B/s]

data/codegolf.stackexchange.com/train-00(…):   0%|          | 0.00/38.6M [00:00<?, ?B/s]

data/codegolf.stackexchange.com/train-00(…):   0%|          | 0.00/39.5M [00:00<?, ?B/s]

data/codereview.meta.stackexchange.com/t(…):   0%|          | 0.00/2.84M [00:00<?, ?B/s]

data/codereview.stackexchange.com/train-(…):   0%|          | 0.00/33.9M [00:00<?, ?B/s]

data/codereview.stackexchange.com/train-(…):   0%|          | 0.00/29.2M [00:00<?, ?B/s]

data/codereview.stackexchange.com/train-(…):   0%|          | 0.00/35.0M [00:00<?, ?B/s]

data/codereview.stackexchange.com/train-(…):   0%|          | 0.00/39.6M [00:00<?, ?B/s]

data/coffee.stackexchange.com/train-0000(…):   0%|          | 0.00/1.55M [00:00<?, ?B/s]

data/coffee.meta.stackexchange.com/train(…):   0%|          | 0.00/94.8k [00:00<?, ?B/s]

data/cogsci.meta.stackexchange.com/train(…):   0%|          | 0.00/685k [00:00<?, ?B/s]

data/cogsci.stackexchange.com/train-0000(…):   0%|          | 0.00/5.70M [00:00<?, ?B/s]

data/computergraphics.meta.stackexchange(…):   0%|          | 0.00/85.4k [00:00<?, ?B/s]

data/computergraphics.stackexchange.com/(…):   0%|          | 0.00/1.87M [00:00<?, ?B/s]

data/conlang.meta.stackexchange.com/trai(…):   0%|          | 0.00/82.8k [00:00<?, ?B/s]

data/conlang.stackexchange.com/train-000(…):   0%|          | 0.00/814k [00:00<?, ?B/s]

data/cooking.meta.stackexchange.com/trai(…):   0%|          | 0.00/1.06M [00:00<?, ?B/s]

data/cooking.stackexchange.com/train-000(…):   0%|          | 0.00/30.6M [00:00<?, ?B/s]

data/craftcms.meta.stackexchange.com/tra(…):   0%|          | 0.00/57.7k [00:00<?, ?B/s]

data/craftcms.stackexchange.com/train-00(…):   0%|          | 0.00/3.98M [00:00<?, ?B/s]

data/crafts.meta.stackexchange.com/train(…):   0%|          | 0.00/220k [00:00<?, ?B/s]

data/crypto.meta.stackexchange.com/train(…):   0%|          | 0.00/568k [00:00<?, ?B/s]

data/crafts.stackexchange.com/train-0000(…):   0%|          | 0.00/2.59M [00:00<?, ?B/s]

data/crypto.stackexchange.com/train-0000(…):   0%|          | 0.00/21.0M [00:00<?, ?B/s]

data/cs.meta.stackexchange.com/train-000(…):   0%|          | 0.00/659k [00:00<?, ?B/s]

data/cseducators.meta.stackexchange.com/(…):   0%|          | 0.00/294k [00:00<?, ?B/s]

data/cs.stackexchange.com/train-00000-of(…):   0%|          | 0.00/24.2M [00:00<?, ?B/s]

data/cseducators.stackexchange.com/train(…):   0%|          | 0.00/4.88M [00:00<?, ?B/s]

data/cstheory.meta.stackexchange.com/tra(…):   0%|          | 0.00/684k [00:00<?, ?B/s]

data/datascience.stackexchange.com/train(…):   0%|          | 0.00/14.9M [00:00<?, ?B/s]

data/datascience.meta.stackexchange.com/(…):   0%|          | 0.00/209k [00:00<?, ?B/s]

data/cstheory.stackexchange.com/train-00(…):   0%|          | 0.00/9.55M [00:00<?, ?B/s]

data/dba.meta.stackexchange.com/train-00(…):   0%|          | 0.00/780k [00:00<?, ?B/s]

data/dba.stackexchange.com/train-00000-o(…):   0%|          | 0.00/33.8M [00:00<?, ?B/s]

data/dba.stackexchange.com/train-00001-o(…):   0%|          | 0.00/34.3M [00:00<?, ?B/s]

data/devops.meta.stackexchange.com/train(…):   0%|          | 0.00/103k [00:00<?, ?B/s]

data/devops.stackexchange.com/train-0000(…):   0%|          | 0.00/3.03M [00:00<?, ?B/s]

data/diy.meta.stackexchange.com/train-00(…):   0%|          | 0.00/432k [00:00<?, ?B/s]

data/diy.stackexchange.com/train-00001-o(…):   0%|          | 0.00/31.4M [00:00<?, ?B/s]

data/diy.stackexchange.com/train-00000-o(…):   0%|          | 0.00/30.4M [00:00<?, ?B/s]

data/drones.meta.stackexchange.com/train(…):   0%|          | 0.00/96.5k [00:00<?, ?B/s]

data/drones.stackexchange.com/train-0000(…):   0%|          | 0.00/664k [00:00<?, ?B/s]

data/drupal.meta.stackexchange.com/train(…):   0%|          | 0.00/567k [00:00<?, ?B/s]

data/drupal.stackexchange.com/train-0000(…):   0%|          | 0.00/34.8M [00:00<?, ?B/s]

data/dsp.stackexchange.com/train-00000-o(…):   0%|          | 0.00/17.4M [00:00<?, ?B/s]

data/earthscience.stackexchange.com/trai(…):   0%|          | 0.00/5.32M [00:00<?, ?B/s]

data/dsp.meta.stackexchange.com/train-00(…):   0%|          | 0.00/207k [00:00<?, ?B/s]

data/economics.meta.stackexchange.com/tr(…):   0%|          | 0.00/396k [00:00<?, ?B/s]

data/earthscience.meta.stackexchange.com(…):   0%|          | 0.00/320k [00:00<?, ?B/s]

data/ebooks.meta.stackexchange.com/train(…):   0%|          | 0.00/94.5k [00:00<?, ?B/s]

data/economics.stackexchange.com/train-0(…):   0%|          | 0.00/9.88M [00:00<?, ?B/s]

data/ebooks.stackexchange.com/train-0000(…):   0%|          | 0.00/1.04M [00:00<?, ?B/s]

data/electronics.stackexchange.com/train(…):   0%|          | 0.00/46.4M [00:00<?, ?B/s]

data/electronics.meta.stackexchange.com/(…):   0%|          | 0.00/1.99M [00:00<?, ?B/s]

data/electronics.stackexchange.com/train(…):   0%|          | 0.00/41.5M [00:00<?, ?B/s]

data/electronics.stackexchange.com/train(…):   0%|          | 0.00/41.4M [00:00<?, ?B/s]

data/electronics.stackexchange.com/train(…):   0%|          | 0.00/43.1M [00:00<?, ?B/s]

data/ell.meta.stackexchange.com/train-00(…):   0%|          | 0.00/1.65M [00:00<?, ?B/s]

data/ell.stackexchange.com/train-00001-o(…):   0%|          | 0.00/25.0M [00:00<?, ?B/s]

data/elementaryos.meta.stackexchange.com(…):   0%|          | 0.00/67.7k [00:00<?, ?B/s]

data/elementaryos.stackexchange.com/trai(…):   0%|          | 0.00/2.46M [00:00<?, ?B/s]

data/emacs.meta.stackexchange.com/train-(…):   0%|          | 0.00/266k [00:00<?, ?B/s]

data/ell.stackexchange.com/train-00000-o(…):   0%|          | 0.00/30.5M [00:00<?, ?B/s]

data/emacs.stackexchange.com/train-00000(…):   0%|          | 0.00/10.3M [00:00<?, ?B/s]

data/engineering.meta.stackexchange.com/(…):   0%|          | 0.00/316k [00:00<?, ?B/s]

data/engineering.stackexchange.com/train(…):   0%|          | 0.00/9.98M [00:00<?, ?B/s]

data/english.meta.stackexchange.com/trai(…):   0%|          | 0.00/5.06M [00:00<?, ?B/s]

data/english.stackexchange.com/train-000(…):   0%|          | 0.00/45.3M [00:00<?, ?B/s]

data/english.stackexchange.com/train-000(…):   0%|          | 0.00/47.8M [00:00<?, ?B/s]

data/english.stackexchange.com/train-000(…):   0%|          | 0.00/45.9M [00:00<?, ?B/s]

data/eosio.meta.stackexchange.com/train-(…):   0%|          | 0.00/24.5k [00:00<?, ?B/s]

data/eosio.stackexchange.com/train-00000(…):   0%|          | 0.00/712k [00:00<?, ?B/s]

data/ethereum.stackexchange.com/train-00(…):   0%|          | 0.00/16.3M [00:00<?, ?B/s]

data/esperanto.stackexchange.com/train-0(…):   0%|          | 0.00/1.82M [00:00<?, ?B/s]

data/esperanto.meta.stackexchange.com/tr(…):   0%|          | 0.00/78.2k [00:00<?, ?B/s]

data/ethereum.meta.stackexchange.com/tra(…):   0%|          | 0.00/199k [00:00<?, ?B/s]

data/expatriates.meta.stackexchange.com/(…):   0%|          | 0.00/163k [00:00<?, ?B/s]

data/expatriates.stackexchange.com/train(…):   0%|          | 0.00/2.74M [00:00<?, ?B/s]

data/expressionengine.meta.stackexchange(…):   0%|          | 0.00/130k [00:00<?, ?B/s]

data/expressionengine.stackexchange.com/(…):   0%|          | 0.00/4.58M [00:00<?, ?B/s]

data/fitness.meta.stackexchange.com/trai(…):   0%|          | 0.00/274k [00:00<?, ?B/s]

data/fitness.stackexchange.com/train-000(…):   0%|          | 0.00/12.4M [00:00<?, ?B/s]

data/freelancing.meta.stackexchange.com/(…):   0%|          | 0.00/124k [00:00<?, ?B/s]

data/freelancing.stackexchange.com/train(…):   0%|          | 0.00/3.37M [00:00<?, ?B/s]

data/french.meta.stackexchange.com/train(…):   0%|          | 0.00/419k [00:00<?, ?B/s]

data/french.stackexchange.com/train-0000(…):   0%|          | 0.00/15.4M [00:00<?, ?B/s]

data/gamedev.meta.stackexchange.com/trai(…):   0%|          | 0.00/981k [00:00<?, ?B/s]

data/gaming.meta.stackexchange.com/train(…):   0%|          | 0.00/4.38M [00:00<?, ?B/s]

data/gamedev.stackexchange.com/train-000(…):   0%|          | 0.00/43.9M [00:00<?, ?B/s]

data/gaming.stackexchange.com/train-0000(…):   0%|          | 0.00/31.6M [00:00<?, ?B/s]

data/gaming.stackexchange.com/train-0000(…):   0%|          | 0.00/27.5M [00:00<?, ?B/s]

data/gardening.meta.stackexchange.com/tr(…):   0%|          | 0.00/297k [00:00<?, ?B/s]

data/gardening.stackexchange.com/train-0(…):   0%|          | 0.00/11.2M [00:00<?, ?B/s]

data/genealogy.stackexchange.com/train-0(…):   0%|          | 0.00/4.30M [00:00<?, ?B/s]

data/genealogy.meta.stackexchange.com/tr(…):   0%|          | 0.00/764k [00:00<?, ?B/s]

data/german.meta.stackexchange.com/train(…):   0%|          | 0.00/848k [00:00<?, ?B/s]

data/german.stackexchange.com/train-0000(…):   0%|          | 0.00/22.1M [00:00<?, ?B/s]

data/gis.meta.stackexchange.com/train-00(…):   0%|          | 0.00/999k [00:00<?, ?B/s]

data/gis.stackexchange.com/train-00000-o(…):   0%|          | 0.00/31.5M [00:00<?, ?B/s]

data/graphicdesign.meta.stackexchange.co(…):   0%|          | 0.00/1.18M [00:00<?, ?B/s]

data/gis.stackexchange.com/train-00001-o(…):   0%|          | 0.00/29.5M [00:00<?, ?B/s]

data/graphicdesign.stackexchange.com/tra(…):   0%|          | 0.00/28.6M [00:00<?, ?B/s]

data/ham.meta.stackexchange.com/train-00(…):   0%|          | 0.00/217k [00:00<?, ?B/s]

data/hardwarerecs.stackexchange.com/trai(…):   0%|          | 0.00/1.66M [00:00<?, ?B/s]

data/hardwarerecs.meta.stackexchange.com(…):   0%|          | 0.00/279k [00:00<?, ?B/s]

data/ham.stackexchange.com/train-00000-o(…):   0%|          | 0.00/6.01M [00:00<?, ?B/s]

data/health.meta.stackexchange.com/train(…):   0%|          | 0.00/565k [00:00<?, ?B/s]

data/health.stackexchange.com/train-0000(…):   0%|          | 0.00/3.27M [00:00<?, ?B/s]

data/hermeneutics.meta.stackexchange.com(…):   0%|          | 0.00/1.07M [00:00<?, ?B/s]

data/hermeneutics.stackexchange.com/trai(…):   0%|          | 0.00/31.3M [00:00<?, ?B/s]

data/hermeneutics.stackexchange.com/trai(…):   0%|          | 0.00/24.7M [00:00<?, ?B/s]

data/hinduism.meta.stackexchange.com/tra(…):   0%|          | 0.00/889k [00:00<?, ?B/s]

data/history.meta.stackexchange.com/trai(…):   0%|          | 0.00/1.18M [00:00<?, ?B/s]

data/hinduism.stackexchange.com/train-00(…):   0%|          | 0.00/19.6M [00:00<?, ?B/s]

data/history.stackexchange.com/train-000(…):   0%|          | 0.00/30.6M [00:00<?, ?B/s]

data/homebrew.meta.stackexchange.com/tra(…):   0%|          | 0.00/118k [00:00<?, ?B/s]

data/homebrew.stackexchange.com/train-00(…):   0%|          | 0.00/6.38M [00:00<?, ?B/s]

data/hsm.meta.stackexchange.com/train-00(…):   0%|          | 0.00/155k [00:00<?, ?B/s]

data/hsm.stackexchange.com/train-00000-o(…):   0%|          | 0.00/4.13M [00:00<?, ?B/s]

data/interpersonal.meta.stackexchange.co(…):   0%|          | 0.00/2.11M [00:00<?, ?B/s]

data/iot.stackexchange.com/train-00000-o(…):   0%|          | 0.00/1.43M [00:00<?, ?B/s]

data/interpersonal.stackexchange.com/tra(…):   0%|          | 0.00/17.2M [00:00<?, ?B/s]

data/iot.meta.stackexchange.com/train-00(…):   0%|          | 0.00/175k [00:00<?, ?B/s]

data/iota.meta.stackexchange.com/train-0(…):   0%|          | 0.00/40.7k [00:00<?, ?B/s]

data/iota.stackexchange.com/train-00000-(…):   0%|          | 0.00/375k [00:00<?, ?B/s]

data/islam.meta.stackexchange.com/train-(…):   0%|          | 0.00/964k [00:00<?, ?B/s]

data/islam.stackexchange.com/train-00000(…):   0%|          | 0.00/15.3M [00:00<?, ?B/s]

data/italian.stackexchange.com/train-000(…):   0%|          | 0.00/2.48M [00:00<?, ?B/s]

data/japanese.meta.stackexchange.com/tra(…):   0%|          | 0.00/712k [00:00<?, ?B/s]

data/italian.meta.stackexchange.com/trai(…):   0%|          | 0.00/224k [00:00<?, ?B/s]

data/japanese.stackexchange.com/train-00(…):   0%|          | 0.00/16.0M [00:00<?, ?B/s]

data/joomla.meta.stackexchange.com/train(…):   0%|          | 0.00/135k [00:00<?, ?B/s]

data/judaism.stackexchange.com/train-000(…):   0%|          | 0.00/37.3M [00:00<?, ?B/s]

data/joomla.stackexchange.com/train-0000(…):   0%|          | 0.00/3.79M [00:00<?, ?B/s]

data/judaism.meta.stackexchange.com/trai(…):   0%|          | 0.00/1.51M [00:00<?, ?B/s]

data/korean.meta.stackexchange.com/train(…):   0%|          | 0.00/84.5k [00:00<?, ?B/s]

data/korean.stackexchange.com/train-0000(…):   0%|          | 0.00/1.44M [00:00<?, ?B/s]

data/languagelearning.stackexchange.com/(…):   0%|          | 0.00/1.41M [00:00<?, ?B/s]

data/latin.meta.stackexchange.com/train-(…):   0%|          | 0.00/262k [00:00<?, ?B/s]

data/languagelearning.meta.stackexchange(…):   0%|          | 0.00/192k [00:00<?, ?B/s]

data/latin.stackexchange.com/train-00000(…):   0%|          | 0.00/5.41M [00:00<?, ?B/s]

data/law.meta.stackexchange.com/train-00(…):   0%|          | 0.00/685k [00:00<?, ?B/s]

data/law.stackexchange.com/train-00000-o(…):   0%|          | 0.00/26.8M [00:00<?, ?B/s]

data/lifehacks.meta.stackexchange.com/tr(…):   0%|          | 0.00/309k [00:00<?, ?B/s]

data/linguistics.meta.stackexchange.com/(…):   0%|          | 0.00/358k [00:00<?, ?B/s]

data/lifehacks.stackexchange.com/train-0(…):   0%|          | 0.00/5.35M [00:00<?, ?B/s]

data/linguistics.stackexchange.com/train(…):   0%|          | 0.00/10.9M [00:00<?, ?B/s]

data/literature.meta.stackexchange.com/t(…):   0%|          | 0.00/892k [00:00<?, ?B/s]

data/literature.stackexchange.com/train-(…):   0%|          | 0.00/4.86M [00:00<?, ?B/s]

data/magento.meta.stackexchange.com/trai(…):   0%|          | 0.00/355k [00:00<?, ?B/s]

data/magento.stackexchange.com/train-000(…):   0%|          | 0.00/25.7M [00:00<?, ?B/s]

data/magento.stackexchange.com/train-000(…):   0%|          | 0.00/22.6M [00:00<?, ?B/s]

data/martialarts.stackexchange.com/train(…):   0%|          | 0.00/6.22M [00:00<?, ?B/s]

data/materials.stackexchange.com/train-0(…):   0%|          | 0.00/2.13M [00:00<?, ?B/s]

data/materials.meta.stackexchange.com/tr(…):   0%|          | 0.00/138k [00:00<?, ?B/s]

data/martialarts.meta.stackexchange.com/(…):   0%|          | 0.00/315k [00:00<?, ?B/s]

data/math.meta.stackexchange.com/train-0(…):   0%|          | 0.00/7.28M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00000-(…):   0%|          | 0.00/52.4M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00001-(…):   0%|          | 0.00/40.7M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00002-(…):   0%|          | 0.00/38.8M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00003-(…):   0%|          | 0.00/36.0M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00004-(…):   0%|          | 0.00/36.3M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00005-(…):   0%|          | 0.00/34.1M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00007-(…):   0%|          | 0.00/34.4M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00008-(…):   0%|          | 0.00/35.5M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00009-(…):   0%|          | 0.00/35.7M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00006-(…):   0%|          | 0.00/35.5M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00011-(…):   0%|          | 0.00/34.2M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00010-(…):   0%|          | 0.00/33.7M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00013-(…):   0%|          | 0.00/36.9M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00012-(…):   0%|          | 0.00/33.9M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00014-(…):   0%|          | 0.00/37.7M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00015-(…):   0%|          | 0.00/36.6M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00016-(…):   0%|          | 0.00/38.0M [00:00<?, ?B/s]

data/math.stackexchange.com/train-00017-(…):   0%|          | 0.00/40.0M [00:00<?, ?B/s]

data/matheducators.meta.stackexchange.co(…):   0%|          | 0.00/257k [00:00<?, ?B/s]

data/math.stackexchange.com/train-00018-(…):   0%|          | 0.00/46.0M [00:00<?, ?B/s]

data/matheducators.stackexchange.com/tra(…):   0%|          | 0.00/11.1M [00:00<?, ?B/s]

data/mathematica.stackexchange.com/train(…):   0%|          | 0.00/36.0M [00:00<?, ?B/s]

data/mathematica.meta.stackexchange.com/(…):   0%|          | 0.00/832k [00:00<?, ?B/s]

data/mathoverflow.net/train-00000-of-000(…):   0%|          | 0.00/39.4M [00:00<?, ?B/s]

data/mathoverflow.net/train-00001-of-000(…):   0%|          | 0.00/31.6M [00:00<?, ?B/s]

data/mathematica.stackexchange.com/train(…):   0%|          | 0.00/31.1M [00:00<?, ?B/s]

data/mathoverflow.net/train-00002-of-000(…):   0%|          | 0.00/35.5M [00:00<?, ?B/s]

data/mechanics.meta.stackexchange.com/tr(…):   0%|          | 0.00/424k [00:00<?, ?B/s]

data/mechanics.stackexchange.com/train-0(…):   0%|          | 0.00/17.1M [00:00<?, ?B/s]

data/meta.askubuntu.com/train-00000-of-0(…):   0%|          | 0.00/4.32M [00:00<?, ?B/s]

data/meta.mathoverflow.net/train-00000-o(…):   0%|          | 0.00/1.61M [00:00<?, ?B/s]

data/meta.serverfault.com/train-00000-of(…):   0%|          | 0.00/2.72M [00:00<?, ?B/s]

data/meta.stackexchange.com/train-00000-(…):   0%|          | 0.00/29.4M [00:00<?, ?B/s]

data/meta.stackexchange.com/train-00001-(…):   0%|          | 0.00/41.5M [00:00<?, ?B/s]

data/meta.stackoverflow.com/train-00000-(…):   0%|          | 0.00/38.6M [00:00<?, ?B/s]

data/meta.superuser.com/train-00000-of-0(…):   0%|          | 0.00/3.51M [00:00<?, ?B/s]

data/moderators.meta.stackexchange.com/t(…):   0%|          | 0.00/191k [00:00<?, ?B/s]

data/moderators.stackexchange.com/train-(…):   0%|          | 0.00/1.28M [00:00<?, ?B/s]

data/monero.meta.stackexchange.com/train(…):   0%|          | 0.00/56.6k [00:00<?, ?B/s]

data/monero.stackexchange.com/train-0000(…):   0%|          | 0.00/1.54M [00:00<?, ?B/s]

data/money.meta.stackexchange.com/train-(…):   0%|          | 0.00/709k [00:00<?, ?B/s]

data/movies.meta.stackexchange.com/train(…):   0%|          | 0.00/1.28M [00:00<?, ?B/s]

data/money.stackexchange.com/train-00000(…):   0%|          | 0.00/43.6M [00:00<?, ?B/s]

data/movies.stackexchange.com/train-0000(…):   0%|          | 0.00/21.3M [00:00<?, ?B/s]

data/music.meta.stackexchange.com/train-(…):   0%|          | 0.00/918k [00:00<?, ?B/s]

data/music.stackexchange.com/train-00000(…):   0%|          | 0.00/44.6M [00:00<?, ?B/s]

data/musicfans.meta.stackexchange.com/tr(…):   0%|          | 0.00/194k [00:00<?, ?B/s]

data/musicfans.stackexchange.com/train-0(…):   0%|          | 0.00/1.39M [00:00<?, ?B/s]

data/mythology.stackexchange.com/train-0(…):   0%|          | 0.00/2.55M [00:00<?, ?B/s]

data/networkengineering.stackexchange.co(…):   0%|          | 0.00/12.5M [00:00<?, ?B/s]

data/mythology.meta.stackexchange.com/tr(…):   0%|          | 0.00/178k [00:00<?, ?B/s]

data/opendata.meta.stackexchange.com/tra(…):   0%|          | 0.00/121k [00:00<?, ?B/s]

data/networkengineering.meta.stackexchan(…):   0%|          | 0.00/324k [00:00<?, ?B/s]

data/opendata.stackexchange.com/train-00(…):   0%|          | 0.00/2.50M [00:00<?, ?B/s]

data/opensource.meta.stackexchange.com/t(…):   0%|          | 0.00/347k [00:00<?, ?B/s]

data/opensource.stackexchange.com/train-(…):   0%|          | 0.00/3.94M [00:00<?, ?B/s]

data/or.meta.stackexchange.com/train-000(…):   0%|          | 0.00/134k [00:00<?, ?B/s]

data/or.stackexchange.com/train-00000-of(…):   0%|          | 0.00/2.75M [00:00<?, ?B/s]

data/outdoors.meta.stackexchange.com/tra(…):   0%|          | 0.00/631k [00:00<?, ?B/s]

data/outdoors.stackexchange.com/train-00(…):   0%|          | 0.00/11.7M [00:00<?, ?B/s]

data/parenting.meta.stackexchange.com/tr(…):   0%|          | 0.00/784k [00:00<?, ?B/s]

data/patents.meta.stackexchange.com/trai(…):   0%|          | 0.00/76.5k [00:00<?, ?B/s]

data/parenting.stackexchange.com/train-0(…):   0%|          | 0.00/21.8M [00:00<?, ?B/s]

data/patents.stackexchange.com/train-000(…):   0%|          | 0.00/3.15M [00:00<?, ?B/s]

data/pets.meta.stackexchange.com/train-0(…):   0%|          | 0.00/512k [00:00<?, ?B/s]

data/pets.stackexchange.com/train-00000-(…):   0%|          | 0.00/7.64M [00:00<?, ?B/s]

data/philosophy.meta.stackexchange.com/t(…):   0%|          | 0.00/854k [00:00<?, ?B/s]

data/photo.meta.stackexchange.com/train-(…):   0%|          | 0.00/1.36M [00:00<?, ?B/s]

data/philosophy.stackexchange.com/train-(…):   0%|          | 0.00/44.8M [00:00<?, ?B/s]

data/physics.stackexchange.com/train-000(…):   0%|          | 0.00/44.2M [00:00<?, ?B/s]

data/physics.stackexchange.com/train-000(…):   0%|          | 0.00/39.1M [00:00<?, ?B/s]

data/physics.stackexchange.com/train-000(…):   0%|          | 0.00/38.0M [00:00<?, ?B/s]

data/physics.meta.stackexchange.com/trai(…):   0%|          | 0.00/3.89M [00:00<?, ?B/s]

data/physics.stackexchange.com/train-000(…):   0%|          | 0.00/36.8M [00:00<?, ?B/s]

data/physics.stackexchange.com/train-000(…):   0%|          | 0.00/35.9M [00:00<?, ?B/s]

data/photo.stackexchange.com/train-00000(…):   0%|          | 0.00/44.9M [00:00<?, ?B/s]

data/pm.stackexchange.com/train-00000-of(…):   0%|          | 0.00/15.0M [00:00<?, ?B/s]

data/pm.meta.stackexchange.com/train-000(…):   0%|          | 0.00/343k [00:00<?, ?B/s]

data/poker.meta.stackexchange.com/train-(…):   0%|          | 0.00/119k [00:00<?, ?B/s]

data/politics.meta.stackexchange.com/tra(…):   0%|          | 0.00/1.76M [00:00<?, ?B/s]

data/politics.stackexchange.com/train-00(…):   0%|          | 0.00/38.5M [00:00<?, ?B/s]

data/portuguese.meta.stackexchange.com/t(…):   0%|          | 0.00/169k [00:00<?, ?B/s]

data/poker.stackexchange.com/train-00000(…):   0%|          | 0.00/2.81M [00:00<?, ?B/s]

data/portuguese.stackexchange.com/train-(…):   0%|          | 0.00/2.97M [00:00<?, ?B/s]

data/puzzling.meta.stackexchange.com/tra(…):   0%|          | 0.00/1.80M [00:00<?, ?B/s]

data/quant.meta.stackexchange.com/train-(…):   0%|          | 0.00/181k [00:00<?, ?B/s]

data/puzzling.stackexchange.com/train-00(…):   0%|          | 0.00/36.0M [00:00<?, ?B/s]

data/quant.stackexchange.com/train-00000(…):   0%|          | 0.00/11.5M [00:00<?, ?B/s]

data/quantumcomputing.meta.stackexchange(…):   0%|          | 0.00/257k [00:00<?, ?B/s]

data/quantumcomputing.stackexchange.com/(…):   0%|          | 0.00/5.27M [00:00<?, ?B/s]

data/raspberrypi.meta.stackexchange.com/(…):   0%|          | 0.00/491k [00:00<?, ?B/s]

data/raspberrypi.stackexchange.com/train(…):   0%|          | 0.00/20.8M [00:00<?, ?B/s]

data/retrocomputing.meta.stackexchange.c(…):   0%|          | 0.00/511k [00:00<?, ?B/s]

data/reverseengineering.meta.stackexchan(…):   0%|          | 0.00/148k [00:00<?, ?B/s]

data/retrocomputing.stackexchange.com/tr(…):   0%|          | 0.00/13.4M [00:00<?, ?B/s]

data/robotics.meta.stackexchange.com/tra(…):   0%|          | 0.00/177k [00:00<?, ?B/s]

data/rpg.stackexchange.com/train-00001-o(…):   0%|          | 0.00/33.3M [00:00<?, ?B/s]

data/robotics.stackexchange.com/train-00(…):   0%|          | 0.00/4.51M [00:00<?, ?B/s]

data/reverseengineering.stackexchange.co(…):   0%|          | 0.00/5.34M [00:00<?, ?B/s]

data/rpg.meta.stackexchange.com/train-00(…):   0%|          | 0.00/5.30M [00:00<?, ?B/s]

data/rpg.stackexchange.com/train-00002-o(…):   0%|          | 0.00/36.8M [00:00<?, ?B/s]

data/rpg.stackexchange.com/train-00000-o(…):   0%|          | 0.00/38.5M [00:00<?, ?B/s]

data/rus.meta.stackexchange.com/train-00(…):   0%|          | 0.00/214k [00:00<?, ?B/s]

data/russian.meta.stackexchange.com/trai(…):   0%|          | 0.00/122k [00:00<?, ?B/s]

data/rus.stackexchange.com/train-00000-o(…):   0%|          | 0.00/22.9M [00:00<?, ?B/s]

data/russian.stackexchange.com/train-000(…):   0%|          | 0.00/7.10M [00:00<?, ?B/s]

data/salesforce.stackexchange.com/train-(…):   0%|          | 0.00/24.1M [00:00<?, ?B/s]

data/salesforce.meta.stackexchange.com/t(…):   0%|          | 0.00/585k [00:00<?, ?B/s]

data/salesforce.stackexchange.com/train-(…):   0%|          | 0.00/23.8M [00:00<?, ?B/s]

data/scicomp.meta.stackexchange.com/trai(…):   0%|          | 0.00/228k [00:00<?, ?B/s]

data/scicomp.stackexchange.com/train-000(…):   0%|          | 0.00/7.76M [00:00<?, ?B/s]

data/scifi.meta.stackexchange.com/train-(…):   0%|          | 0.00/4.59M [00:00<?, ?B/s]

data/scifi.stackexchange.com/train-00000(…):   0%|          | 0.00/46.2M [00:00<?, ?B/s]

data/scifi.stackexchange.com/train-00001(…):   0%|          | 0.00/44.1M [00:00<?, ?B/s]

data/security.meta.stackexchange.com/tra(…):   0%|          | 0.00/1.09M [00:00<?, ?B/s]

data/security.stackexchange.com/train-00(…):   0%|          | 0.00/36.8M [00:00<?, ?B/s]

data/security.stackexchange.com/train-00(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/serverfault.com/train-00000-of-0000(…):   0%|          | 0.00/44.4M [00:00<?, ?B/s]

data/serverfault.com/train-00003-of-0000(…):   0%|          | 0.00/42.2M [00:00<?, ?B/s]

data/serverfault.com/train-00002-of-0000(…):   0%|          | 0.00/38.8M [00:00<?, ?B/s]

data/sharepoint.meta.stackexchange.com/t(…):   0%|          | 0.00/314k [00:00<?, ?B/s]

data/serverfault.com/train-00001-of-0000(…):   0%|          | 0.00/36.2M [00:00<?, ?B/s]

data/serverfault.com/train-00004-of-0000(…):   0%|          | 0.00/41.2M [00:00<?, ?B/s]

data/sharepoint.stackexchange.com/train-(…):   0%|          | 0.00/37.4M [00:00<?, ?B/s]

data/sitecore.meta.stackexchange.com/tra(…):   0%|          | 0.00/102k [00:00<?, ?B/s]

data/skeptics.meta.stackexchange.com/tra(…):   0%|          | 0.00/2.07M [00:00<?, ?B/s]

data/sitecore.stackexchange.com/train-00(…):   0%|          | 0.00/6.07M [00:00<?, ?B/s]

data/skeptics.stackexchange.com/train-00(…):   0%|          | 0.00/15.8M [00:00<?, ?B/s]

data/softwareengineering.meta.stackexcha(…):   0%|          | 0.00/3.31M [00:00<?, ?B/s]

data/softwareengineering.stackexchange.c(…):   0%|          | 0.00/49.9M [00:00<?, ?B/s]

data/softwareengineering.stackexchange.c(…):   0%|          | 0.00/40.6M [00:00<?, ?B/s]

data/softwareengineering.stackexchange.c(…):   0%|          | 0.00/42.9M [00:00<?, ?B/s]

data/softwarerecs.meta.stackexchange.com(…):   0%|          | 0.00/686k [00:00<?, ?B/s]

data/softwarerecs.stackexchange.com/trai(…):   0%|          | 0.00/9.37M [00:00<?, ?B/s]

data/sound.meta.stackexchange.com/train-(…):   0%|          | 0.00/185k [00:00<?, ?B/s]

data/space.meta.stackexchange.com/train-(…):   0%|          | 0.00/801k [00:00<?, ?B/s]

data/sound.stackexchange.com/train-00000(…):   0%|          | 0.00/12.1M [00:00<?, ?B/s]

data/space.stackexchange.com/train-00000(…):   0%|          | 0.00/20.2M [00:00<?, ?B/s]

data/spanish.meta.stackexchange.com/trai(…):   0%|          | 0.00/614k [00:00<?, ?B/s]

data/spanish.stackexchange.com/train-000(…):   0%|          | 0.00/11.3M [00:00<?, ?B/s]

data/sports.meta.stackexchange.com/train(…):   0%|          | 0.00/335k [00:00<?, ?B/s]

data/sports.stackexchange.com/train-0000(…):   0%|          | 0.00/4.15M [00:00<?, ?B/s]

data/sqa.meta.stackexchange.com/train-00(…):   0%|          | 0.00/140k [00:00<?, ?B/s]

data/sqa.stackexchange.com/train-00000-o(…):   0%|          | 0.00/13.0M [00:00<?, ?B/s]

data/stackapps.com/train-00000-of-00001.(…):   0%|          | 0.00/1.03M [00:00<?, ?B/s]

data/stats.meta.stackexchange.com/train-(…):   0%|          | 0.00/1.80M [00:00<?, ?B/s]

data/stats.stackexchange.com/train-00000(…):   0%|          | 0.00/32.8M [00:00<?, ?B/s]

data/stats.stackexchange.com/train-00001(…):   0%|          | 0.00/31.0M [00:00<?, ?B/s]

data/stats.stackexchange.com/train-00002(…):   0%|          | 0.00/32.6M [00:00<?, ?B/s]

data/stellar.meta.stackexchange.com/trai(…):   0%|          | 0.00/25.3k [00:00<?, ?B/s]

data/stellar.stackexchange.com/train-000(…):   0%|          | 0.00/463k [00:00<?, ?B/s]

data/superuser.com/train-00000-of-00006.(…):   0%|          | 0.00/43.5M [00:00<?, ?B/s]

data/superuser.com/train-00001-of-00006.(…):   0%|          | 0.00/41.1M [00:00<?, ?B/s]

data/superuser.com/train-00002-of-00006.(…):   0%|          | 0.00/42.9M [00:00<?, ?B/s]

data/superuser.com/train-00003-of-00006.(…):   0%|          | 0.00/43.5M [00:00<?, ?B/s]

data/superuser.com/train-00004-of-00006.(…):   0%|          | 0.00/45.1M [00:00<?, ?B/s]

data/superuser.com/train-00005-of-00006.(…):   0%|          | 0.00/43.8M [00:00<?, ?B/s]

data/sustainability.meta.stackexchange.c(…):   0%|          | 0.00/167k [00:00<?, ?B/s]

data/sustainability.stackexchange.com/tr(…):   0%|          | 0.00/3.46M [00:00<?, ?B/s]

data/tex.meta.stackexchange.com/train-00(…):   0%|          | 0.00/2.36M [00:00<?, ?B/s]

data/tex.stackexchange.com/train-00000-o(…):   0%|          | 0.00/32.7M [00:00<?, ?B/s]

data/tex.stackexchange.com/train-00002-o(…):   0%|          | 0.00/30.9M [00:00<?, ?B/s]

data/tex.stackexchange.com/train-00001-o(…):   0%|          | 0.00/32.2M [00:00<?, ?B/s]

data/tex.stackexchange.com/train-00003-o(…):   0%|          | 0.00/32.5M [00:00<?, ?B/s]

data/tex.stackexchange.com/train-00004-o(…):   0%|          | 0.00/31.5M [00:00<?, ?B/s]

data/tezos.meta.stackexchange.com/train-(…):   0%|          | 0.00/22.9k [00:00<?, ?B/s]

data/tezos.stackexchange.com/train-00000(…):   0%|          | 0.00/523k [00:00<?, ?B/s]

data/tor.meta.stackexchange.com/train-00(…):   0%|          | 0.00/89.1k [00:00<?, ?B/s]

data/tor.stackexchange.com/train-00000-o(…):   0%|          | 0.00/2.22M [00:00<?, ?B/s]

data/travel.meta.stackexchange.com/train(…):   0%|          | 0.00/1.80M [00:00<?, ?B/s]

data/travel.stackexchange.com/train-0000(…):   0%|          | 0.00/38.0M [00:00<?, ?B/s]

data/tridion.meta.stackexchange.com/trai(…):   0%|          | 0.00/190k [00:00<?, ?B/s]

data/tridion.stackexchange.com/train-000(…):   0%|          | 0.00/4.69M [00:00<?, ?B/s]

data/ukrainian.meta.stackexchange.com/tr(…):   0%|          | 0.00/177k [00:00<?, ?B/s]

data/ukrainian.stackexchange.com/train-0(…):   0%|          | 0.00/2.82M [00:00<?, ?B/s]

data/unix.meta.stackexchange.com/train-0(…):   0%|          | 0.00/1.58M [00:00<?, ?B/s]

data/unix.stackexchange.com/train-00000-(…):   0%|          | 0.00/39.8M [00:00<?, ?B/s]

data/unix.stackexchange.com/train-00001-(…):   0%|          | 0.00/37.7M [00:00<?, ?B/s]

data/unix.stackexchange.com/train-00002-(…):   0%|          | 0.00/35.8M [00:00<?, ?B/s]

data/unix.stackexchange.com/train-00003-(…):   0%|          | 0.00/36.6M [00:00<?, ?B/s]

data/vegetarianism.stackexchange.com/tra(…):   0%|          | 0.00/1.04M [00:00<?, ?B/s]

data/ux.stackexchange.com/train-00000-of(…):   0%|          | 0.00/48.7M [00:00<?, ?B/s]

data/vegetarianism.meta.stackexchange.co(…):   0%|          | 0.00/145k [00:00<?, ?B/s]

data/ux.meta.stackexchange.com/train-000(…):   0%|          | 0.00/615k [00:00<?, ?B/s]

data/vi.meta.stackexchange.com/train-000(…):   0%|          | 0.00/190k [00:00<?, ?B/s]

data/webapps.meta.stackexchange.com/trai(…):   0%|          | 0.00/406k [00:00<?, ?B/s]

data/webapps.stackexchange.com/train-000(…):   0%|          | 0.00/13.0M [00:00<?, ?B/s]

data/vi.stackexchange.com/train-00000-of(…):   0%|          | 0.00/6.48M [00:00<?, ?B/s]

data/webmasters.stackexchange.com/train-(…):   0%|          | 0.00/21.8M [00:00<?, ?B/s]

data/webmasters.meta.stackexchange.com/t(…):   0%|          | 0.00/407k [00:00<?, ?B/s]

data/windowsphone.meta.stackexchange.com(…):   0%|          | 0.00/97.0k [00:00<?, ?B/s]

data/windowsphone.stackexchange.com/trai(…):   0%|          | 0.00/1.12M [00:00<?, ?B/s]

data/woodworking.meta.stackexchange.com/(…):   0%|          | 0.00/121k [00:00<?, ?B/s]

data/woodworking.stackexchange.com/train(…):   0%|          | 0.00/4.72M [00:00<?, ?B/s]

data/wordpress.meta.stackexchange.com/tr(…):   0%|          | 0.00/1.03M [00:00<?, ?B/s]

data/wordpress.stackexchange.com/train-0(…):   0%|          | 0.00/24.4M [00:00<?, ?B/s]

data/wordpress.stackexchange.com/train-0(…):   0%|          | 0.00/23.1M [00:00<?, ?B/s]

data/workplace.meta.stackexchange.com/tr(…):   0%|          | 0.00/2.74M [00:00<?, ?B/s]

data/workplace.stackexchange.com/train-0(…):   0%|          | 0.00/44.2M [00:00<?, ?B/s]

data/worldbuilding.meta.stackexchange.co(…):   0%|          | 0.00/4.67M [00:00<?, ?B/s]

data/workplace.stackexchange.com/train-0(…):   0%|          | 0.00/47.1M [00:00<?, ?B/s]

data/worldbuilding.stackexchange.com/tra(…):   0%|          | 0.00/50.2M [00:00<?, ?B/s]

data/worldbuilding.stackexchange.com/tra(…):   0%|          | 0.00/44.8M [00:00<?, ?B/s]

data/worldbuilding.stackexchange.com/tra(…):   0%|          | 0.00/44.7M [00:00<?, ?B/s]

data/writers.meta.stackexchange.com/trai(…):   0%|          | 0.00/1.28M [00:00<?, ?B/s]

data/writers.stackexchange.com/train-000(…):   0%|          | 0.00/34.3M [00:00<?, ?B/s]

data/worldbuilding.stackexchange.com/tra(…):   0%|          | 0.00/45.4M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/10807695 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/94 [00:00<?, ?it/s]

Dataset({
    features: ['qid', 'question', 'answers', 'date', 'metadata'],
    num_rows: 10807695
})
{'qid': Value('int64'), 'question': Value('string'), 'answers': List({'answer_id': Value('int64'), 'author': Value('string'), 'author_id': Value('int64'), 'author_profile': Value('string'), 'pm_score': Value('int64'), 'selected': Value('bool'), 'text': Value('string')}), 'date': Value('string'), 'metadata': List(Value('string'))}


####**Comments / clarity**
* Loads a StackExchange/StackOverflow-style dataset (train split).
* Printing features helps verify which fields exist (important because later hit missing column issues).

**Convert a sample to pandas**


In [ ]:
sample_size = 50000  # adjust as needed
ds_small = ds.shuffle(seed=42).select(range(sample_size)) # shuffle(seed=42) gives reproducible sampling.
df = ds_small.to_pandas()
df.head()

,qid,question,answers,date,metadata
0,12891264,<p>I am using jQuery fileupload plugin and I w...,"[{'answer_id': 12891484, 'author': 'Reflective...",2012/10/15,"[https://Stackoverflow.com/questions/12891264,..."
1,67231378,<p>I have created a custom cms components that...,"[{'answer_id': 67233102, 'author': 'Krzysztof ...",2021/04/23,"[https://Stackoverflow.com/questions/67231378,..."
2,588860,<p>When reading about the Big Bang you’ll comm...,"[{'answer_id': 588879, 'author': 'drfk', 'auth...",2020/10/22,[https://physics.stackexchange.com/questions/5...
3,141736,<p>I've got a flight back to my own country wi...,"[{'answer_id': 141737, 'author': 'Hilmar', 'au...",2019/07/09,[https://travel.stackexchange.com/questions/14...
4,1484683,<p>I have a piece of code that works fine in t...,"[{'answer_id': 1485644, 'author': 'Rishav Rast...",2009/09/27,"[https://Stackoverflow.com/questions/1484683, ..."


**Text cleaning + build *doc_text***

**Strip HTML from Q/A text and build the final retrieval document (doc_text)**

In [ ]:
def strip_html(text: str) -> str:
    # Ensure the input is always treated as a string (handles NaN/None safely)
    text = str(text)

    # Remove any HTML tags like <p>, <code>, <pre>, etc.
    # This reduces noise in embeddings and improves retrieval quality.
    text = re.sub(r"<[^>]+>", " ", text)

    # Collapse repeated whitespace/newlines into a single space and trim ends
    text = re.sub(r"\s+", " ", text).strip()
    return text

# Clean the raw question text (which may contain HTML formatting)
#df["question_clean"] = df["question"].apply(strip_html)

# Clean the selected "best answer" text (also may contain HTML/code tags)
#df["doc_text"] = (


# Build the final text document that will be embedded + indexed for retrieval.
# Combining Q + A improves retrieval because the answer contains solution keywords.


**Observations**

This is a standard RAG pattern: embed “question + best answer” as one unit.

The dataframe now contains:
* question_clean (HTML stripped)
* top_answer_clean (HTML stripped)
* doc_text (concatenation of both)

**Insights**
* This is a critical RAG preprocessing step. HTML-heavy text degrades embedding quality because embeddings pick up markup tokens instead of meaning.
* Cleaning also helps the generator: when retrieved sources are cleaner, the LLM is less likely to “echo” weird HTML artifacts.
* Building doc_text as “Question + Best Answer” generally improves retrieval vs question-only, because:
    * the answer includes key implementation details (function names, code patterns, edge cases)
    * the question is often short/ambiguous

**Brief Summary**

This cell prepares the dataset for retrieval by:
* cleaning noisy HTML from questions and answers, and
* creating a single searchable text field (doc_text) that becomes the unit embed and store in FAISS.


**Build a “best answer” and compose *doc_text***

In [ ]:
# Select best answer (selected=True first, else highest pm_score)
def pick_best_answer(ans_arr):
    # HF datasets may store "answers" as a numpy array or a Python list,
    # so we normalize to a Python list for consistent processing.
    if isinstance(ans_arr, np.ndarray):
        ans_list = ans_arr.tolist()
    elif isinstance(ans_arr, list):
        ans_list = ans_arr
    else:
        # If the data type is unexpected, we return empty string (no answer)
        return ""

    # If no answers exist for this question, return empty
    if len(ans_list) == 0:
        return ""

    # Prefer the accepted/selected answer if present (usually the best answer)
    selected = [a for a in ans_list if isinstance(a, dict) and a.get("selected") is True]

    # If there's no accepted answer, consider all answers that are dict-like
    candidates = selected if selected else [a for a in ans_list if isinstance(a, dict)]

    # If still nothing usable, fallback to string conversion of the first item
    if not candidates:
        return str(ans_list[0])

    # Choose the answer with the highest pm_score (proxy for quality/upvotes)
    best = max(candidates, key=lambda a: a.get("pm_score", 0))

    # Return the raw answer HTML/text field
    return best.get("text", "")

# Create a single top answer for each question (one “best answer” per row)
df["top_answer"] = df["answers"].apply(pick_best_answer)

# Clean HTML/noisy formatting from question + selected answer
df["question_clean"] = df["question"].apply(strip_html)
df["top_answer_clean"] = df["top_answer"].apply(strip_html)

# Compose the retrieval document (this is what is embed/index in FAISS)
# Putting Question + Top Answer together improves retrieval because the answer contains key solution terms.
df["doc_text"] = "Question: " + df["question_clean"] + "\n\nTop Answer: " + df["top_answer_clean"]

# Preview what the retriever will index
df[["qid", "doc_text"]].head()

,qid,doc_text
0,12891264,Question: I am using jQuery fileupload plugin ...
1,67231378,Question: I have created a custom cms componen...
2,588860,Question: When reading about the Big Bang you’...
3,141736,Question: I've got a flight back to my own cou...
4,1484683,Question: I have a piece of code that works fi...


**Observations**
* This creates a consistent “one document per post” representation.
* Using accepted answers (when available) improves retrieval quality because accepted answers are usually best.

**Insights**
* This is a key RAG design choice: the embedding content that contains the solution, not just the question.
* pm_score is a practical heuristic: it approximates “answer quality” without training a model.

**Brief Summary**

Turns a multi-answer structure into a single, clean “Question + Best Answer” document for embedding and search.

**Verify HTML tags are removed**

In [ ]:
df[["qid","question_clean","top_answer_clean","doc_text"]].head(2)

,qid,question_clean,top_answer_clean,doc_text
0,12891264,I am using jQuery fileupload plugin and I want...,"Looking at the library code, seems all events ...",Question: I am using jQuery fileupload plugin ...
1,67231378,I have created a custom cms components that ha...,The fields exposed in the OCC api are driven b...,Question: I have created a custom cms componen...


**RAG EDA**

**Purpose:** Introduce corpus-quality checks (RAG-style “EDA”).

**Observations/Insights**
* Good structure: RAG EDA is about text length, emptiness, noise (code/URLs), duplicates—not correlations.

In [ ]:
# --- RAG EDA: corpus quality + quick signals (compact) ---

def text_stats(s: pd.Series, name: str):
    lens = s.fillna("").astype(str).str.len()
    words = s.fillna("").astype(str).str.split().str.len()
    print(f"\n{name}:")
    print(f"  empty%     : {(lens == 0).mean():.3%}")
    print(f"  chars (p50): {lens.median():.0f} | (p90): {lens.quantile(0.90):.0f} | (max): {lens.max():.0f}")
    print(f"  words (p50): {words.median():.0f} | (p90): {words.quantile(0.90):.0f} | (max): {words.max():.0f}")

print("Rows:", len(df), "| Unique qid:", df["qid"].nunique())
print("Duplicate qid rows:", (len(df) - df["qid"].nunique()))

# Empty/length stats
text_stats(df["question_clean"], "question_clean")
text_stats(df["top_answer_clean"], "top_answer_clean")
text_stats(df["doc_text"], "doc_text (what was embed)")

# Simple noise signals: code + URLs can affect embeddings/retrieval
has_code = df["doc_text"].str.contains(r"```|<code>|pd\.|import |def |SELECT |{", case=False, na=False)
has_url  = df["doc_text"].str.contains(r"http[s]?://|www\.", case=False, na=False)
print("\nSignal coverage:")
print(f"  code-like docs: {has_code.mean():.1%}")
print(f"  url-containing : {has_url.mean():.1%}")

# Inspect extremes (helps tune snippet caps and token truncation)
print("\nShortest doc_text examples:")
display(df.loc[df["doc_text"].str.len().nsmallest(3).index, ["qid","question_clean","top_answer_clean"]])

print("\nLongest doc_text examples:")
display(df.loc[df["doc_text"].str.len().nlargest(3).index, ["qid","question_clean","top_answer_clean"]])

Rows: 50000 | Unique qid: 49798
Duplicate qid rows: 202

question_clean:
  empty%     : 0.002%
  chars (p50): 687 | (p90): 2073 | (max): 44245
  words (p50): 108 | (p90): 278 | (max): 4152

top_answer_clean:
  empty%     : 0.004%
  chars (p50): 533 | (p90): 1709 | (max): 42807
  words (p50): 80 | (p90): 259 | (max): 5522

doc_text (what was embed):
  empty%     : 0.000%
  chars (p50): 1417 | (p90): 3537 | (max): 68126
  words (p50): 213 | (p90): 494 | (max): 9051

Signal coverage:
  code-like docs: 60.6%
  url-containing : 20.4%

Shortest doc_text examples:


,qid,question_clean,top_answer_clean
24660,101392,"As title said, I can what tool to read .evt fi...","Um, Event Viewer?"
4964,159230,Is there any way to unwear winterbash hats?,Just click on that hat again to un-wear it.
2945,5230588,I want to measure the execution time for php s...,Use microtime . Make sure to look at example #2.



Longest doc_text examples:


,qid,question_clean,top_answer_clean
32733,236728,I have written a Matrix library that contains ...,using namespace std; Never do that; certainly ...
34829,66671755,I have below json response array which I am ge...,You could use the HTML anchor tag to link to e...
5016,52063394,Can anybody tell me how to stop this line from...,"This was a tough cookie, but I enjoyed the cha..."


**Observations**

Measure corpus properties that affect retrieval and generation (length distribution, empties, noisy docs).

This quantifies:
* duplicates (qid repeats)
* empty rates
* “code-like” and “URL-like” prevalence

This inspects shortest/longest docs (important for truncation decisions).

**Insights**
* Long-tail doc length is the main reason for context overflow warnings later.
* Code/URL heavy docs are where dense retrieval sometimes struggles; reranker helps.

**Brief Summary**

Builds a fast “health report” for the corpus to guide truncation, retrieval settings, and reliability gates.

**Check all the colums**

In [ ]:
df.columns

Index(['qid', 'question', 'answers', 'date', 'metadata', 'question_clean',
       'top_answer', 'top_answer_clean', 'doc_text'],
      dtype='object')

**Create embeddings with SentenceTransformer**

**Purpose:** Encode all doc_text into vectors for similarity search.

In [ ]:
# Load a strong lightweight embedding model (good speed/quality tradeoff)
# all-MiniLM-L6-v2 is popular because it's fast and performs well for semantic search
embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# Convert the corpus into a Python list of strings (avoid NaNs)
texts = df["doc_text"].fillna("").tolist()

# Encode documents into vector embeddings
emb = embedder.encode(
    texts,
    convert_to_numpy=True,        # returns a NumPy array instead of torch tensor
    normalize_embeddings=True,    # unit-normalize vectors so dot-product == cosine similarity
    show_progress_bar=True        # visual progress for long runs
)

# Shape should be (num_docs, embedding_dim)
emb.shape

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

(50000, 384)

**Observations**
* This normalize embeddings → makes cosine similarity equivalent to dot product.

**Insights**
* Normalization is important because FAISS IndexFlatIP uses inner product. With normalized embeddings, it effectively becomes cosine similarity.
* There's a dense vector representation of every Q+A document. This is the foundation of the retrieval system.
* Since embeddings are normalized, this allows for FAISS inner-product search (IndexFlatIP) and it behaves like cosine similarity.
*

**Brief Summary**

Creates the embedding matrix used to build the FAISS vector index.

**Build FAISS index and retrieve top-k**

Introduce indexing/retrieval. Starts vector search.

In [ ]:
d = emb.shape[1]              # embedding dimension
index = faiss.IndexFlatIP(d)  # inner product index (cosine if embeddings normalized)
index.add(emb)                # add all doc vectors

def retrieve(query, k=5):
    # Embed the query in the same vector space
    q_emb = embedder.encode([query], convert_to_numpy=True, normalize_embeddings=True)

    # Search index; returns scores and ids
    scores, ids = index.search(q_emb, k)
    return ids[0], scores[0]

**Observations**
* This is a standard “dense retrieval” baseline.

**Insights**
* IndexFlatIP is exact search (not approximate), which is fine for 50k docs in Colab and keeps results stable for evaluation.

**Brief Summary**

Creates FAISS similarity search and a reusable retrieval function.

**Test retrieval - quick sanity**

In [ ]:
query = "How do I merge two pandas dataframes on a column?"
ids, scores = retrieve(query, k=5)
df.loc[ids, ["doc_text"]].head()

,doc_text
3765,Question: I am looking to merge two data frame...
1118,Question: I'm getting two different merge beha...
10415,Question: I have 2 dataframe listed as follow ...
10884,Question: I have two data frames df1 ## day ti...
36859,Question: I have 2 dataframes and I need to ge...


**Observations**
* This gives an immediate “does retrieval make sense?” check.

**Insights**
* Great habit: early retrieval sanity check catches embedding/index mistakes before adding generation.
* Validates that FAISS returns reasonable docs for a sample query.

**Production sytle settings**

In [ ]:
# ===== Production-style Settings =====
RAG_SETTINGS = {
    "faiss_k": 20,            # retrieve top-20 candidates
    "rerank_top_k": 10,       # reranker keeps top-10
    "context_k": 3,           # only pass top-3 sources to the LLM
    "min_score": 0.20,        # gate: refuse if evidence is weak
    "q_chars": 250,           # cap question snippet per source
    "a_chars": 600,           # cap answer snippet per source
    "max_input_tokens": 3800, # prevent exceeding 4096 context models
    "max_new_tokens": 220,    # keep answers short/cheap
}

**Purpose**
* Centralize tunable knobs for reranking, context size, truncation, and generation controls.


**Generation + citations (RAG answer) - Prompt Builder**

In [ ]:
def build_prompt(query: str, src_rows: pd.DataFrame, settings=RAG_SETTINGS):
    sources = []

    # Loop through retrieved source rows (top-k after reranking)
    for i, r in enumerate(src_rows.itertuples(index=False), start=1):

        # Truncate question and answer snippets to control prompt size (token budget)
        q = (r.question_clean or "")[:settings["q_chars"]]
        a = (r.top_answer_clean or "")[:settings["a_chars"]]

        # Add a structured, numbered source block
        # SOURCE [i] becomes the citation reference (later attached as [1], [2], etc.)
        sources.append(
            f"SOURCE [{i}] qid={r.qid} score={r.score:.3f}\n"
            f"Q: {q}\n"
            f"A: {a}\n"
        )

    # Combine all source blocks into one context string
    context = "\n\n".join(sources)

    # Final prompt:
    # - tells model to use ONLY provided sources (RAG grounding)
    # - forces bullet output and prevents meta-text
    # - prevents hallucinated columns/tables/fields
    # - includes ### ANSWER delimiter to help parsing output
    return f"""You are a technical assistant.
Answer the user's question using ONLY the sources below.

Output rules:
- Output ONLY 3–5 bullet points starting with "- ".
- Be specific and code-first when possible.
- Do not add headings or meta-instructions.
- Do NOT invent specific column names (e.g., 'Id'). Use placeholders like 'key_col' unless a column name is explicitly shown in the sources.
- Do NOT force a join type ('inner'/'left'/'outer') unless the sources explicitly recommend one; otherwise mention common options briefly.
- Do NOT introduce new tables/fields (e.g., "Table A", "last month") unless explicitly present

User question: {query}

Sources:
{context}

### ANSWER
"""

**Observations**
* Added rules based on real failure modes (invented columns, invented entities, join-type overconfidence).
* determines how much source text the LLM sees (q_chars, a_chars)
* determines whether the LLM stays grounded
* determines whether output is easy to parse (the ### ANSWER delimiter)


**Insights**
* GenAI engineering works: iterate prompt constraints based on observed failure cases, then add deterministic post-processing for remaining glitches.
    * **Token budget control:** It caps source snippets to reduce context overflow and lower latency.
    * **Grounding rules:** It explicitly say “use ONLY sources,” which reduces hallucinations.
    * **Output format contract:** bullet-only response makes answers consistent and easy to test.
    * **Failure-mode prevention:** the last three rules are responses to real failure modes it encountered:
        * inventing column names ('Id')
        * forcing join types (inner/left/outer)
        * inventing fake entities (“Table A”, “last month”)
    * **Delimiting marker (### ANSWER):** makes bullet extraction robust by separating instructions from the answer.

**Brief Summary**
* Creates a controlled prompt that encourages grounded, concise bullet answers.
* This function transforms retrieved sources into a structured prompt:
    * gives the LLM the relevant evidence,
    * constrains output to a consistent bullet format,
    * reduces hallucination risk,
    * and keeps prompts small enough to run within the model’s context window.

**Function-only description (what build_prompt() does)**

```
build_prompt():
```
1. Takes the user query + top retrieved source rows,
2. truncates each source’s question and answer to fixed character budgets,
3. formats them as numbered “SOURCE [i] … Q: … A: …” blocks, and
4. returns an instruction prompt that forces bullet output and prevents common hallucinations.




**Baseline “retrieve_with_sources” (FAISS only)**

**Purpose:** Return not just ids/scores, but the actual source rows (qid + cleaned text) for inspection.


In [ ]:
def retrieve_with_sources(query, k=5):
    # Retrieve the top-k nearest documents from the FAISS index
    # ids = row indices in df, scores = similarity scores from FAISS
    ids, scores = retrieve(query, k=k)

    # Pull the corresponding source fields from df so we can inspect them
    rows = df.loc[ids, ["qid", "question_clean", "top_answer_clean"]].copy()

    # Attach similarity scores so we can rank/diagnose retrieval quality
    rows["score"] = scores

    # Reset index so the output table is clean (0..k-1)
    return rows.reset_index(drop=True)

# Example query: pandas merge question
retrieve_with_sources("How do I merge two pandas dataframes on a column?", k=5)

,qid,question_clean,top_answer_clean,score
0,56117107,"I am looking to merge two data frames, first b...",To merge two dataframes by multiple columns yo...,0.720267
1,36440803,I'm getting two different merge behaviors usin...,you may try like this: &lt;body&gt; &lt;div cl...,0.711348
2,39764652,I have 2 dataframe listed as follow df Type Br...,You need concat : print (pd.concat([df1[['Type...,0.689243
3,45847812,I have two data frames df1 ## day time temp ac...,"Just add a column to each one, before you merg...",0.680010
4,67971801,I have 2 dataframes and I need to get a new da...,SQL SUM function return type is mapped to Long...,0.678186


**Observations**
* **Note:** Note: these scores are FAISS similarity scores (different scale from reranker scores).
* Retrieved 5 results (k=5), each with:
    * qid (unique identifier for the post)
    * question_clean (cleaned question text)
    * top_answer_clean (cleaned best answer text)
    * score (FAISS similarity score)
* The results are clearly on-topic for merges:
    * merging on multiple columns
    * merge behavior differences
    * combining dataframes / outer join
* Scores range roughly 0.678 → 0.720, with the top result being 0.720267.

**Insights**
* **Retrieval debugging lens:** it allows verification that the index is returning relevant sources before it involve the LLM.
* The FAISS similarity scores are relatively close together, which is normal for semantically similar queries. The key is the ranking order and whether the retrieved sources are relevant.
* It can also see a classic real-world issue: one retrieved item looks less relevant (“SQL SUM function return type…”).

  This is a great example of why reranking helps later—dense retrieval sometimes pulls near-neighbors that share generic language but aren’t truly relevant.

**Summary**

FAISS retriever can find relevant StackOverflow posts for a user query and returns them in a format that’s useful for inspection and downstream prompting (qid + cleaned Q/A + similarity).

**Function-only description (```retrieve_with_sources```)**

```
retrieve_with_sources()
```
* sanity checking retrieval quality,
* debugging bad retrieval cases,
* and providing source text for the RAG pipeline.




**Load an instruct LLM - Phi-3 Mini**

**Purpose:** Introduce the generative component of the RAG system (the “G” in RAG).

In [ ]:
MODEL_ID = "microsoft/Phi-3-mini-4k-instruct"

# BitsAndBytes quantization config:
# Loads model weights in 4-bit to reduce VRAM usage (important for Colab T4)
bnb = BitsAndBytesConfig(
    load_in_4bit=True,              # enable 4-bit loading
    bnb_4bit_quant_type="nf4",      # NF4 is a strong 4-bit quantization scheme
    bnb_4bit_compute_dtype=torch.float16,  # compute in fp16 for speed on GPU
    bnb_4bit_use_double_quant=True, # improves quality of 4-bit quantization
)

# Tokenizer converts text → token IDs for the model
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

# Load the model:
# - quantization_config makes it 4-bit
# - device_map="auto" places model layers on GPU automatically if available
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb,
    device_map="auto"
)

print("Loaded:", MODEL_ID)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

Loaded: microsoft/Phi-3-mini-4k-instruct


**Observations**
* This is a stable approach for Colab T4: 4-bit quantization keeps memory manageable.
* device_map="auto" is convenient and usually works well.
* Retrieval (FAISS) is already built, now this adds generation

**Insights**
* This is “production-ready”: it mirrors how teams reduce model footprint to cut cost/latency.
* In RAG, generation is usually the slowest step, so later latency profiling is important.
* **4-bit quantization** is a practical engineering tradeoff:
    * much lower VRAM usage
    * allows running models that might otherwise not fit on T4
* LLM is now ready for inference (generation) in Colab with limited GPU memory.

*NOTE: This was developed in Google Colab which allows runtime CPU*

**Brief Summary**

Loads a lightweight instruction-tuned LLM (Phi-3-mini-4k-instruct) using 4-bit quantization so that the RAG assistant can generate answers efficiently on Colab GPUs.

**Cross-encoder re-ranker to improve retrieval precision (FAISS → rerank → top-k)**

In [ ]:
reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

def retrieve_reranked(query, faiss_k=20, final_k=10):
    """
    1) Retrieve faiss_k candidates from FAISS (bi-encoder)
    2) Re-rank with cross-encoder
    3) Return top final_k doc row indices
    """
    # Step A: FAISS retrieval
    cand_ids, cand_scores = retrieve(query, k=faiss_k)  # existing retrieve()

    # Step B: Build pairs (query, doc_text)
    cand_texts = df.loc[cand_ids, "doc_text"].fillna("").tolist()
    pairs = [(query, t) for t in cand_texts]

    # Step C: Cross-encoder scores
    ce_scores = reranker.predict(pairs)  # higher = more relevant

    # Step D: Sort candidates by ce_scores
    order = np.argsort(-ce_scores)
    reranked_ids = cand_ids[order][:final_k]
    reranked_scores = ce_scores[order][:final_k]

    return reranked_ids, reranked_scores

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

**Observations**
```
retrieve_reranked(query, faiss_k, final_k):
```
1. retrieves faiss_k candidate documents from FAISS quickly,
2. scores each (query, doc_text) pair with the cross-encoder,
3. returns the top final_k document ids + their reranker scores.

**Insights**
* **FAISS retrieval** is fast but can return “near matches” that are not the best answer.
* The **cross-encoder** reads the query and doc together and can better judge relevance.
* Industry-standard pattern:
    * **bi-encoder (fast recall) → cross-encoder (precision rerank)**

**Summary**

Loads a cross-encoder reranker and defines retrieve_reranked(), enables the rerank of FAISS candidates for higher precision retrieval—critical for better RAG answers.


**Select the top reranked source rows to use as LLM context (context_k)**

In [ ]:
def retrieve_sources(query: str, settings=RAG_SETTINGS):
    # Step 1: Retrieve candidates using FAISS, then rerank them using the cross-encoder
    # ids = row indices into df, ce_scores = reranker relevance scores (higher is better)
    ids, ce_scores = retrieve_reranked(
        query,
        faiss_k=settings["faiss_k"],        # number of FAISS candidates to consider
        final_k=settings["rerank_top_k"]    # number of candidates to keep after reranking
    )

    # Step 2: Pull the actual source text fields to use for prompting (and traceability)
    # This keeps the "evidence" available in a readable form
    rows = df.loc[ids, ["qid", "question_clean", "top_answer_clean"]].copy()

    # Attach reranker scores so we can gate/refuse based on evidence strength
    rows["score"] = ce_scores

    # Reset index for cleaner display / stable iteration in build_prompt()
    rows = rows.reset_index(drop=True)

    # Step 3: Only pass the top context_k sources into the LLM prompt
    # This reduces noise + token usage and prevents context window overflow
    return rows.head(settings["context_k"])

**Observations**
* Returns dataframe will have up to ```context_k``` rows
* Each row will contain:
    * ```qid```
    * ```question_clean```
    * ```top_answer_clean```
    * ```score``` (cross-encoder reranker score)

**Insights**

This is the **core control point** in the RAG pipeline. From an employer’s perspective, it shows understanding “production tradeoffs”:
* **Precision vs Cost:** reranking gives better top results, but it’s slower — so reranking only a limited set (```faiss_k```).
* **Reliability vs Noise:** sends only the top ```context_k``` sources into the model — fewer sources means:
    * less prompt bloat
    * fewer irrelevant distractors
    * fewer token-overflow warnings
    * more consistent generation
* **Safety gating:** the score enables the ```min_score``` refusal logic — refusing is better than hallucinating.

**Summary**

This defines ```retrieve_sources()```, which retrieves and reranks documents, then returns the top evidence snippets (top ```context_k```) used to ground the LLM response.

**Function-only description (what ```retrieve_sources()``` does)**

```retrieve_sources(query, settings):```
1. retrieves faiss_k candidates using FAISS + embeddings,
2. reranks them with a cross-encoder and keeps rerank_top_k,
3. returns only the top context_k rows (qid + cleaned question/answer + reranker score) for the LLM prompt.

**Deterministically attach citations to each bullet**

In [ ]:
def tokenize(s):
    # Lowercase to make matching case-insensitive
    s = s.lower()

    # Replace non-alphanumeric characters with spaces (removes punctuation/html remnants)
    # Keeps underscores because code identifiers sometimes contain them
    s = re.sub(r"[^a-z0-9_]+", " ", s)

    # Return a set of tokens, dropping very short tokens (len <= 2) to reduce noise
    return set(t for t in s.split() if len(t) > 2)

def attach_citations(bullets_text, sources_df, top_n=1):
    """
    Adds citations like [1] to the end of each bullet line by:
    1) tokenizing each source (question_clean + top_answer_clean)
    2) tokenizing each bullet line
    3) scoring overlap(bullet_tokens ∩ source_tokens)
    4) attaching the best-matching source id(s) as citations

    sources_df should be the same DataFrame you pass into build_prompt (top context_k rows).
    """

    # Precompute token sets per source for fast matching
    src_tokens = []
    for i, r in enumerate(sources_df.itertuples(index=False), start=1):
        # Combine question+answer so tokens include both problem and solution language
        tokens = tokenize((r.question_clean or "") + " " + (r.top_answer_clean or ""))
        src_tokens.append((i, tokens))  # i corresponds to SOURCE [i]

    fixed = []
    for ln in bullets_text.splitlines():
        # Only process bullet lines
        if not ln.startswith("- "):
            continue

        # Tokenize the bullet content
        btok = tokenize(ln)

        # Score each source by how many tokens overlap with the bullet
        scored = [(len(btok & stok), sid) for sid, stok in src_tokens]
        scored.sort(reverse=True)  # higher overlap first

        # Choose the top_n best sources with overlap > 0
        chosen = [sid for overlap, sid in scored[:top_n] if overlap > 0]

        # If no overlap at all, fall back to citing source [1]
        if not chosen:
            chosen = [1]

        # Build citation string like [1] or [1][3]
        cite = "".join([f"[{sid}]" for sid in chosen])

        # Remove any citations already present (avoid duplicates), then append our citation
        ln = re.sub(r"\[\d+\]", "", ln).strip()
        fixed.append(f"{ln} {cite}")

    return "\n".join(fixed)

**Observations/Insights**

Why this matters for GenAI/RAG:
* LLMs are inconsistent about citing sources even when asked.
* Instead of relying on the model, it enforces citations deterministically.
* This turns citations from a “best effort” behavior into a guaranteed contract.

It also improves evaluation story:
* this can measure “citation compliance rate” as an objective metric
* and confidently claim answers are grounded in retrieved evidence

**Summary**

This implements a deterministic method to attach citations to RAG answers. It matches each bullet to the most relevant retrieved source using token overlap and appends citations like [1], ensuring high citation compliance and improved trustworthiness.

**Function-only description**
* ```tokenize(s)```: converts text into a set of meaningful tokens (lowercased, punctuation removed, short tokens dropped).
* ```attach_citations(bullets_text, sources_df, top_n)```: for each bullet, finds which source text overlaps most with that bullet and appends the source index as a citation.

**Limit bullet output to a clean, consistent 3–5 bullet**

In [ ]:
def polish_bullets(bullets: str, max_bullets=5) -> str:
    # Keep only lines that are bullet points (must start with "- ")
    lines = [ln.strip() for ln in bullets.splitlines() if ln.strip().startswith("- ")]

    # Enforce an upper bound on how many bullets we return (default 5)
    lines = lines[:max_bullets]

    fixed = []
    for ln in lines:
        # Ensure each bullet ends with a period for consistent presentation
        if not ln.endswith("."):
            ln += "."
        fixed.append(ln)

    # Return a clean bullet list joined by newlines
    return "\n".join(fixed)

**Observations/Insights**

This enforces a consistent “contract” for assistant’s output:
* LLMs can return extra lines, headings, or mixed formatting.
* Evaluations (citation compliance, grounding checks) work best when output is predictable.
* This treats GenAI output as something that is validated and standardize, not just “whatever the model prints.”

Also: by restricting to 3–5 bullets, it reduces:
* rambling answers
* token usage
* user cognitive load

**Summary of the output/effect**

This is a helper that cleans and standardizes the final answer to:
* a maximum of 5 bullets,
* consistent punctuation,
* and bullet-only format.

**Function-only description**

```polish_bullets()``` takes a multi-line string and returns a clean bullet list by:
* filtering only lines that start with - ,
* keeping at most max_bullets,
* and adding a period at the end of each bullet if missing.

**Enforce LLM context-window safety**

In [ ]:
def tokenize_truncate(prompt: str, max_input_tokens: int):
    """
    Tokenize the prompt and truncate it to max_input_tokens so the model
    doesn't exceed its context window (e.g., Phi-3 mini has ~4096 tokens).

    Strategy:
    - Keep the *last* tokens because they usually contain:
      (a) the retrieved sources (most important evidence)
      (b) the user question
      (c) the "### ANSWER" marker
    """
    # Convert the full prompt string into token IDs (no automatic truncation here)
    enc = tokenizer(prompt, return_tensors="pt", truncation=False)
    input_ids = enc["input_ids"][0]  # shape: (num_tokens,)

    # If prompt is too long, keep only the last max_input_tokens
    if input_ids.numel() > max_input_tokens:
        input_ids = input_ids[-max_input_tokens:]  # keep tail tokens only

        # Rebuild the encoding dict using the truncated input_ids
        enc = {"input_ids": input_ids.unsqueeze(0)}

        # Create a matching attention_mask (all ones = all tokens are "real")
        enc["attention_mask"] = torch.ones_like(enc["input_ids"])

    # Move tensors to the same device as the LLM (GPU if available)
    return {k: v.to(llm.device) for k, v in enc.items()}

**Observations/Insights**
* LLMs have a **hard context window limit** (Phi-3 mini ≈ 4096 tokens).
* RAG prompts can grow quickly because they include multiple retrieved sources.
* Without truncation:
    * runtime errors
    * silent truncation in the wrong place
    * slower inference
    * inconsistent answers

Keeping the **tail** is for prompt structure and puts the most important content (sources + question + ### ANSWER) near the end.

**Summary**

The input prompt stays within a fixed token budget by truncating it safely, preventing context overflow and stabilizing inference.

**Function-only description**

```tokenize_truncate(prompt, max_input_tokens):```
* tokenizes a long prompt,
* trims it down to max_input_tokens by keeping the last tokens,
* rebuilds the attention mask,
* and moves everything to the LLM device for generation.

**Generate an LLM completion safely**

In [ ]:
def generate_llm(prompt: str, settings=RAG_SETTINGS):
    # Tokenize the prompt and truncate it to avoid exceeding the model context window
    # (e.g., Phi-3 mini ~4096 tokens). This returns tensors on the LLM device.
    inputs = tokenize_truncate(prompt, max_input_tokens=settings["max_input_tokens"])

    # Disable gradient tracking since we're doing inference (faster + less memory)
    with torch.no_grad():
        out = llm.generate(
            **inputs,
            max_new_tokens=settings["max_new_tokens"],  # control response length
            do_sample=False,                            # deterministic output (repeatable)
            repetition_penalty=1.05,                    # reduces repetitive phrasing
            eos_token_id=tokenizer.eos_token_id,        # stop at EOS token
        )

    # Decode the generated tokens back into text
    full = tokenizer.decode(out[0], skip_special_tokens=True)

    # Some models may include (or partially echo) the prompt in the decoded output.
    # If the prompt appears, return only the text after the prompt; else return full.
    return full.split(prompt, 1)[-1].strip() if prompt in full else full.strip()

**Observations/Insights**

This is the "engine" for the RAG assistant, it shows:.
* **Production awareness:** it enforces a token budget to prevent “4096 token overflow” errors.
* **Reproducibility:** deterministic decoding supports consistent evaluation (important when measuring reliability and latency).
* **Performance hygiene:** using ```torch.no_grad()``` is correct for inference.

*One subtle risk:*
* ```full.split(prompt, 1)``` only works if the decoded output contains the exact prompt text. Because this truncates tokens, the *string prompt*  might not match perfectly—so the fallback else ```full.strip()``` is necessary. The later bullet extraction (using ### ANSWER) is what truly keeps output clean.

**Summary**

```generate_llm()``` which runs safe and repeatable LLM generation by truncating long prompts, disabling gradients, using deterministic decoding, and returning only the completion text.

**Function-only description**

```generate_llm(prompt, settings):```
* tokenizes the prompt (with truncation),
* generates up to max_new_tokens tokens using the LLM,
* decodes the output into text,
* and returns the response (attempting to remove any prompt echo if present).

**Utilities for rag_qa()**

In [ ]:
# ==========================
# Utilities: RAG Guardrails
# - output cleanup
# - bullet extraction
# - deterministic citations
# - grounding validation
# ==========================

def _tok(s: str) -> Set[str]:
    # tokenizes text into a set of keywords used for overlap checks.
    s = (s or "").lower()
    s = re.sub(r"[^a-z0-9_]+", " ", s)
    return set(t for t in s.split() if len(t) > 2)

def clean_bullet_line(ln: str) -> str:
    # removes unwanted “Document:” spillover that models sometimes append inline.
    ln = re.split(r"\bDocument:\b", ln, maxsplit=1)[0].strip()
    return ln

def fix_ens_glitch(text: str) -> str:
    # fixes recurring model artifact (Ens0... → Ensure).
    text = re.sub(r"\bEns0[a-zA-Z]*\b", "Ensure", text)
    return text

def strip_doc_spillover(text: str) -> str:
    # Remove any appended doc-like blocks that models sometimes emit
    # e.g., "Document: Title: ... Description: ... Content: ..."
    text = re.split(r"\bDocument:\b", text, maxsplit=1)[0]
    text = re.split(r"\bTitle:\b", text, maxsplit=1)[0]
    text = re.split(r"\bDescription:\b", text, maxsplit=1)[0]
    text = re.split(r"\bKeywords:\b", text, maxsplit=1)[0]
    text = re.split(r"\bContent:\b", text, maxsplit=1)[0]
    return text.strip()

def extract_bullets_only(text: str, max_bullets=5):
    # ensures the answer is only bullets and only after the ### ANSWER
    # delimiter (prevents prompt echo).
    if "### ANSWER" in text:
        text = text.split("### ANSWER", 1)[-1]
    text = re.sub(r"\s-\s", "\n- ", text.strip())

    lines = [ln.strip() for ln in text.splitlines()]
    bullets = []
    for ln in lines:
        if ln.startswith("- "):
            bullets.append(clean_bullet_line(ln))
    return "\n".join(bullets[:max_bullets])

def attach_citations_to_bullets(bullets_text: str, sources_df, top_n=1):
    """
    Adds citations like [1] to each bullet based on keyword overlap with sources.
    sources_df should be the DataFrame returned by retrieve_sources() (already top context_k).
    """
    # Build token sets for each source (1-indexed)
    src_tokens = []
    for i, r in enumerate(sources_df.itertuples(index=False), start=1):
        tokens = _tok((r.question_clean or "") + " " + (r.top_answer_clean or ""))
        src_tokens.append((i, tokens))

    fixed = []
    for ln in bullets_text.splitlines():
        ln = ln.strip()
        if not ln.startswith("- "):
            continue

        bt = _tok(ln)
        scored = sorted(((len(bt & st), sid) for sid, st in src_tokens), reverse=True)

        chosen = [sid for overlap, sid in scored[:top_n] if overlap > 0]
        if not chosen:
            chosen = [1]  # fallback to best source

        cite = "".join(f"[{sid}]" for sid in chosen)
        ln = re.sub(r"\[\d+\]", "", ln).strip()  # remove any existing citations
        fixed.append(f"{ln} {cite}")

    return "\n".join(fixed)

def bullets_supported_by_sources(bullets_text: str, sources_df, min_overlap=2) -> bool:
    # grounding validator — each bullet must overlap with at least one source (prevents drifting answers).
    src_tok = [
         _tok((r.question_clean or "") + " " + (r.top_answer_clean or ""))
        for r in sources_df.itertuples(index=False)
    ]
    for r in sources_df.itertuples(index=False):
        src_tok.append(_tok((r.question_clean or "") + " " + (r.top_answer_clean or "")))

    for ln in bullets_text.splitlines():
        if not ln.startswith("- "):
            continue
        ln_clean = re.sub(r"\[\d+\]", "", ln)
        bt = _tok(ln)
        best = max((len(bt & st) for st in src_tok), default=0)
        if best < min_overlap:
            return False
    return True

**Final RAG pipline**

In [ ]:
def rag_qa(query: str, settings=RAG_SETTINGS):
    # 1) retrieve evidence (reranked, top context_k)
    sources = retrieve_sources(query, settings=settings)

    # 2) refuse if evidence is weak (min_score)
    if sources["score"].max() < settings["min_score"]:
        return "I don't have enough evidence to answer.", sources

    # 3) Build prompt (already capped per-source)
    prompt = build_prompt(query, sources, settings=settings)

    # 4) Generate with token-safe truncation
    raw = generate_llm(prompt, settings=settings)
    raw = strip_doc_spillover(raw)

    # 5) Clean output → bullets only → polish → fix artifacts
    bullets = extract_bullets_only(raw, max_bullets=5)
    bullets = polish_bullets(bullets, max_bullets=5)
    bullets = fix_ens_glitch(bullets)
    bullets = re.sub(r"\bEnsure include\b", "Ensure you include", bullets)

    # Optional: soften hard-coded "inner" wording if it appears
    bullets = bullets.replace("choose 'inner' join option", "choose `how` based on your goal (inner/left/outer)")

    if not bullets.strip():
        return "I don't have enough evidence to answer.", sources

    # 6) Attach citations ONCE (deterministic)
    bullets = attach_citations_to_bullets(bullets, sources, top_n=1)

    # 7) Validate grounding; refuse if bullets don’t match sources
    if not bullets_supported_by_sources(bullets, sources, min_overlap=2):
        return "I don't have enough evidence to answer.", sources

    return bullets, sources

**Observations/Insights**

GenAI reliability engineering, not just “call a model”:
* **Deterministic citations:** don’t trust the model to cite; enforce it.
* **Grounding validation:** verify that answers are supported by retrieved evidence.
* **Fail-safe behavior:** refuse when evidence is weak or output is ungrounded.
* **Output normalization:** control formatting for evaluation + user experience.
* **Clear pipeline stages:** retrieve → generate → validate → return

**Summary**

This implements the final **production-type RAG inference loop:**
* retrieve evidence via reranker,
* generate an answer with strict formatting,
* sanitize output artifacts,
* attach citations deterministically,
* validate grounding,
* refuse safely when evidence is insufficient.

In [ ]:
llm = model          # Phi-3 model is currently named `model`
llm_tokenizer = tokenizer

**Evaluate retrieval quality with Hit@k**

**Purpose:** baseline FAISS vs reranked retrieval

In [ ]:
def first_sentence(text):
    # Convert to string (safe for NaN/None), normalize whitespace
    text = str(text)
    text = re.sub(r"\s+", " ", text).strip()

    # Split into sentences using punctuation boundaries
    parts = re.split(r"(?<=[.!?])\s+", text)

    # Return the first sentence as a more realistic “short query”
    return parts[0] if parts else text


def eval_hit_at_k(eval_idx, k_list=(1,3,5,10), mode="baseline", faiss_k=20):
    """
    Compute Hit@k over a set of evaluation indices.
    - A "hit" occurs when the retrieved list contains the query's own qid
      within the top-k results (self-retrieval).
    - mode="baseline": uses FAISS retrieval only
    - mode="rerank": uses FAISS candidates + cross-encoder reranking
    """
    hits = {k: 0 for k in k_list}
    n = len(eval_idx)

    for idx in tqdm(eval_idx, desc=f"Hit@k ({mode})"):
        qid_true = df.loc[idx, "qid"]

        # Use first sentence to reduce information leakage and mimic short real queries
        query = first_sentence(df.loc[idx, "question_clean"])

        # Retrieve top results
        if mode == "baseline":
            ids, _ = retrieve(query, k=max(k_list))  # FAISS only
        else:
            ids, _ = retrieve_reranked(query, faiss_k=faiss_k, final_k=max(k_list))  # reranked

        # Convert retrieved doc row indices -> qids
        retrieved_qids = df.loc[ids, "qid"].to_numpy()

        # Count hits at each k
        for k in k_list:
            if qid_true in retrieved_qids[:k]:
                hits[k] += 1

    # Return a simple table of Hit@k results
    return pd.DataFrame([{"k": k, "Hit@k": hits[k]/n} for k in k_list])


# Filter out extremely short questions (often ambiguous / low signal)
valid_len_threshold = 30
valid_idx = df.index[df["question_clean"].fillna("").str.len() > valid_len_threshold].to_numpy()

# Build a stable eval sample (repeatable because rng seed fixed)
eval_size = 300
rng_seed = 42
rng = np.random.default_rng(42)

# Randomly pick eval_size examples
eval_idx = rng.choice(valid_idx, size=min(eval_size, len(valid_idx)), replace=False)

# ===== Evaluation Settings (Retrieval) =====
k_list = (1, 3, 5, 10)
faiss_k_for_rerank = 20
query_style = "first_sentence(question_clean)"
final_k = max(k_list)

print("\n=== Retrieval Evaluation Settings ===")
print(f"eval_size: {len(eval_idx)} (requested: {eval_size})")
print(f"valid_len_threshold: > {valid_len_threshold} chars")
print(f"rng_seed: {rng_seed}")
print(f"k_list: {k_list}")
print(f"query_style: {query_style}")
print(f"faiss_k_for_rerank: {faiss_k_for_rerank}")
print(f"final_k (max k): {final_k}")
print(f"context_k_for_generation: {RAG_SETTINGS.get('context_k')}")
print(f"rerank_top_k: {RAG_SETTINGS.get('rerank_top_k')}")
print(f"min_score_gate: {RAG_SETTINGS.get('min_score')}")
print("====================================\n")

# Run baseline and reranked retrieval evaluation
res_base = eval_hit_at_k(eval_idx, mode="baseline")
res_rer  = eval_hit_at_k(eval_idx, mode="rerank", faiss_k=20)

# Compare results side-by-side and compute delta
cmp = res_base.merge(res_rer, on="k", suffixes=("_baseline","_rerank"))
cmp["delta"] = cmp["Hit@k_rerank"] - cmp["Hit@k_baseline"]
display(cmp)


=== Retrieval Evaluation Settings ===
eval_size: 300 (requested: 300)
valid_len_threshold: > 30 chars
rng_seed: 42
k_list: (1, 3, 5, 10)
query_style: first_sentence(question_clean)
faiss_k_for_rerank: 20
final_k (max k): 10
context_k_for_generation: 3
rerank_top_k: 10
min_score_gate: 0.2



Hit@k (rerank): 100%|██████████| 300/300 [00:47<00:00,  6.35it/s]


,k,Hit@k_baseline,Hit@k_rerank,delta
0,1,0.760000,0.876667,0.116667
1,3,0.816667,0.880000,0.063333
2,5,0.820000,0.880000,0.060000
3,10,0.843333,0.880000,0.036667


**Build a final “baseline vs rerank” comparison table and compute uplift (delta)**

**Observations**

Evaluation Settings
* eval_size: 300
* valid question length: > 30 chars
* rng_seed: 42
* k_list: (1, 3, 5, 10)
* query_style: first_sentence(question_clean) ✅ (leakage-reduced)
* faiss_k_for_rerank: 20
* context_k_for_generation: 3
* erank_top_k: 10
* min_score_gate: 0.2



| k  | baseline | rerank | delta       |
| -- | -------- | ------ | ----------- |
| 1  | 0.7600   | 0.8767 | **+0.1167** |
| 3  | 0.8167   | 0.8800 | **+0.0633** |
| 5  | 0.8200   | 0.8800 | **+0.0600** |
| 10 | 0.8433   | 0.8800 | **+0.0367** |

Key takeaways:
* Reranking improves Hit@k at every k (largest gain is at k=1).
* Baseline FAISS is already decent (0.76 Hit@1), but reranking makes it much stronger.

**Insights**
* Hit@1 is the most meaningful RAG retrieval metric (In RAG, the generator is highly sensitive to the top-ranked sources—so improving top-1 relevance is a big win).
* Reranker gives a +11.6 point improvement in Hit@1, which is huge. (This demonstrates that “FAISS-only retrieval is good, but reranking makes it production-grade.”)
* Using **first_sentence(question_clean)** is a smart choice:
    * It makes evaluation more realistic because users often ask short queries.
    * It reduces “information leakage” (it's not handing the full post to retrieval).
* This supports project narrative:
    * Improved retrieval quality with a cross-encoder reranker and validated it quantitatively.

**Summary**

This evaluates retrieval performance and proves that reranking significantly improves relevance—especially at the top result (Hit@1). The reranker is a meaningful upgrade for the RAG system.

**Function only description**
* ```first_sentence(text)```: returns only the first sentence of the question (realistic short query).
* ```eval_hit_at_k(...)```: computes Hit@k for baseline or reranked retrieval.

In [ ]:
# Manually store the baseline Hit@k results (from baseline evaluation run)
baseline = pd.DataFrame({
    "k": [1, 3, 5, 10],
    "Hit@k_baseline": [0.774, 0.838, 0.846, 0.864]
})

# Merge baseline results with rerank results (res_rerank)
# res_rerank is expected to have columns: ["k", "Hit@k"]
comparison = baseline.merge(res_rer, on="k").rename(columns={"Hit@k": "Hit@k_rerank"})

# Compute improvement from reranking
comparison["delta"] = comparison["Hit@k_rerank"] - comparison["Hit@k_baseline"]

# Display the final comparison table
display(comparison)

,k,Hit@k_baseline,Hit@k_rerank,delta
0,1,0.774,0.876667,0.102667
1,3,0.838,0.880000,0.042000
2,5,0.846,0.880000,0.034000
3,10,0.864,0.880000,0.016000


**Observations**

Comparision tables shows:
* k=1: baseline 0.774 → rerank 0.876 → +0.1027
* k=3: baseline 0.838 → rerank 0.880 → +0.0420
* k=5: baseline 0.846 → rerank 0.880 → +0.0340
* k=10: baseline 0.864 → rerank 0.880 → +0.0160

So reranking helps most at **Hit@1**, and gains taper off at larger k.

**Insights**
* Cross-encoder rerankers primarily improve top-ranked precision, which is why Hit@1 improves the most.
* The small negative at k=10 isn’t a problem in practice.
* In production RAG, you rarely care about top-10 recall as much as top-1/top-3 because:
    * I only pass a few sources (context_k=3) into the LLM anyway
    * the model’s answer quality depends most on the first few sources

**Summary**

This produces a clean baseline vs rerank comparison and shows that reranking delivers the biggest lift at Hit@1 (+0.08), which directly improves the quality of evidence fed into generation.

**Generation reliability test: measure refusal rate + citation compliance (with sample failure logging)**

In [ ]:
CITE_ANY = re.compile(r"\[\d+\]")  # matches citations like [1], [12]

def citation_compliant(answer: str) -> bool:
    """
    Returns True if:
    - the model refused (refusal is acceptable), OR
    - every bullet line (if bullets exist) contains at least one citation [n], OR
    - if no bullets exist, the answer contains at least one citation somewhere.
    """
    ans = (answer or "").strip()

    # Refusals are considered compliant (we'd rather refuse than hallucinate)
    if ans == "I don't have enough evidence to answer.":
        return True

    # Extract bullet lines only
    bullets = [ln.strip() for ln in ans.splitlines() if ln.strip().startswith("- ")]

    # If bullet output exists, every bullet must have a citation
    if bullets:
        return all(CITE_ANY.search(b) for b in bullets)

    # If it's not bullet-form, require at least one citation in the text
    return bool(CITE_ANY.search(ans))


# Sample size for reliability check
test_n = 30
rng = np.random.default_rng(123)

# test_idx uses valid_idx from earlier evaluation sampling
test_idx = rng.choice(valid_idx, size=min(test_n, len(valid_idx)), replace=False)

rows = []
fail_examples = []

for idx in tqdm(test_idx, desc="Gen reliability"):
    # Use first sentence as a more realistic short query (reduces “leakage”)
    q = first_sentence(df.loc[idx, "question_clean"])

    # Run full RAG pipeline (retrieve → generate → clean → cite → validate/refuse)
    ans, src = rag_qa(q)

    refused = (ans.strip() == "I don't have enough evidence to answer.")
    compliant = citation_compliant(ans)

    rows.append({
        "refused": refused,
        "citation_compliant": compliant
    })

    # Log up to 3 examples where the system answered but violated citation rules
    if (not refused) and (not compliant) and len(fail_examples) < 3:
        fail_examples.append((q, ans))


out = pd.DataFrame(rows)
answer_rate = 1 - out["refused"].mean()
out.to_csv("gen_reliability_results.csv", index=False)

# Report key reliability metrics
print("Refusal rate:", out["refused"].mean())
print("Citation compliance rate:", out["citation_compliant"].mean())
print("Answer rate:", answer_rate)

# Show a few examples of failures (if any)
if fail_examples:
    print("\n--- Sample failures (up to 3) ---")
    for q, ans in fail_examples:
        print("\nQ:", q)
        print("A:", ans[:600])

Gen reliability: 100%|██████████| 30/30 [05:44<00:00, 11.50s/it]

Refusal rate: 0.16666666666666666
Citation compliance rate: 1.0
Answer rate: 0.8333333333333334


**Observations**
* 30 queries (dev-sized sample), and it completed successfully.
* **Refusal rate** = 0.1667 → 5 out of 30 queries were refused.
* **Citation compliance rate** = 1.0 → every non-refusal answer follows the citation policy (strong reliability signal).
* **Answer rate** = 0.8333 → the assistant answered ~83% of the time under the current safety gates.

**Pipeline**
* Since the attach citations are deterministically, you should see citation compliance near 1.0
* Refusal rate will depend on ```min_score, context_k,``` and the grounding check (previously observed ~0.26)

**Insights**
* This is a **production-style evaluation**. It’s not just “does it run?”—it measures **trust signals**.
* **Refusal rate** is a *quality/safety tradeoff knob:*
    * Higher refusals → safer, less hallucination risk
    * Lower refusals → more coverage, but higher risk
* **Citation compliance** is the backbone of credibility for RAG:
    * If citations drop, you can’t claim answers are grounded.
* Using ```first_sentence()``` is smart:
    * It makes queries shorter/noisier, closer to real user inputs.
    * It reduces inflated metrics that come from copying the full question text.
* This is a good coverage vs safety balance for a general StackOverflow RAG assistant:
    * ~17% refusals is reasonable because many first-sentence queries are vague or underspecified.
    * 100% citation compliance is a standout feature — it demonstrates solving a common RAG failure mode.

**Summary**

A quick “reliability dashboard” for GenAI assistant:
* how often it refuses,
* how consistently it cites evidence,
* and examples of failures to debug.

This shows GenAI requires **evaluation beyond accuracy.**

**Latency benchmark: measure runtime breakdown (FAISS retrieval vs reranking vs full RAG generation) **

In [ ]:
lat_n = 30
rng = np.random.default_rng(7)

# Sample 30 “valid” questions (valid_idx defined earlier)
lat_idx = rng.choice(valid_idx, size=min(lat_n, len(valid_idx)), replace=False)

times = []
for idx in tqdm(lat_idx, desc="Latency bench"):
    # Use first sentence as the query (more realistic, consistent with eval strategy)
    query = first_sentence(df.loc[idx, "question_clean"])

    # Measure FAISS retrieval time (dense retrieval only)
    t0 = time.perf_counter()
    ids_base, _ = retrieve(query, k=10)
    t1 = time.perf_counter()

    # Measure reranking time (FAISS candidates + cross-encoder scoring)
    ids_rer, _ = retrieve_reranked(query, faiss_k=20, final_k=10)
    t2 = time.perf_counter()

    # Measure full RAG inference time (includes retrieval + rerank + LLM generation + cleanup + citations)
    ans, _ = rag_qa(query)
    t3 = time.perf_counter()

    # Store component timings in milliseconds
    times.append({
        "faiss_retrieval_ms": (t1 - t0) * 1000,
        "rerank_ms": (t2 - t1) * 1000,
        "generation_ms": (t3 - t2) * 1000,
        "end_to_end_ms": (t3 - t0) * 1000,
    })

lat = pd.DataFrame(times)

# Summary table: mean, median (50%), 90th percentile, max
display(lat.describe(percentiles=[0.5, 0.9]).T[["mean","50%","90%","max"]])

Latency bench: 100%|██████████| 30/30 [05:59<00:00, 11.97s/it]


,mean,50%,90%,max
faiss_retrieval_ms,17.201443,16.556779,20.229268,24.293581
rerank_ms,147.846922,141.562354,177.309046,248.744395
generation_ms,11802.669243,11391.229366,17654.546827,18259.764426
end_to_end_ms,11967.717608,11542.895000,17853.100817,18428.083004


**Observations**

Latency summary (30 queries) shows:
* **FAISS retrieval**
    * mean 17.20 ms, p50 16.56 ms, p90 20.23 ms, max 24.30 ms
* **Rerank**
    * mean 147.85 ms, p50 141.56 ms, p90 177.31 ms, max 248.74 ms
* **Generation**
    * mean 11803 ms (~ 11.80s), p50 11391 ms (~11.39s), p90 11654 (11.65s), max 18251 ms (18.25s)
* **End-to-end**
    * mean 11200 ms (11.20s), p50 11542 ms (11.54s), p90 17853 ms (11.85s), max 18429 ms (18.43s)

Verdict: **generation dominates** total runtime; retrieval and reranking are tiny in comparison.

**Insights**
* **FAISS retrieval is essentially “free”** at ~18ms. (which is excellent)
* **Reranking adds ~0.15 seconds**, which is modest relative to total time, and already proved it boosts Hit@1 substantially. This is a great tradeoff.
* **LLM generation is the bottleneck** (11–18 seconds). That’s normal for Colab + small GPU and explains why product teams optimize generation first (smaller model, fewer tokens, caching, batching).
* The p90 end-to-end (~18s) suggests a real-world system would need:
    * caching for repeated questions,
    * streaming responses,
    * or faster inference hardware/models for a “snappy” UX.

**Summary**

The latency benchmark shows FAISS retrieval is fast (~18ms) and reranking adds a small overhead (~152ms), while LLM generation dominates runtime (~11.9s mean, ~18s p90). This confirms reranking is a cost-effective quality improvement, and the primary production bottleneck is generation latency.

###**Conclusion and Overall Performance**

This notebook show a **production-style, general StackOverflow RAG assistant** with the right system components and the right evaluation mindset:
* **Two-stage retrieval:** FAISS dense retrieval for speed + cross-encoder reranking for precision.
* **Controlled generation:** short, bullet-only answers with token-budget protection.
* **Reliability guardrails:** deterministic citations + grounding check + refusal policy when evidence is weak.
* **Measured performance:** retrieval quality (Hit@k), reliability (refusal + citation compliance), and latency breakdown.

####**Overall performance**

**Retrieval quality (baseline vs rerank)**
* **Hit@1:** baseline 0.774 → rerank 0.876 → +1.026
* **Hit@3:** baseline 0.838 → rerank 0.880 → +0.042
* **Hit@5:** baseline 0.846 → rerank 0.880 → +0.034
* **Hit@10:** baseline 0.864 → rerank 0.880 → +0.016

**Generation reliability (30-query sample)**
* Answer rate: 0.833
* Refusal rate: 0.167
* Citation compliance: 1.0 ✅

**Latency (30-query benchmark; averages)**
* FAISS retrieval: ~17 ms
* Rerank: ~147 ms
* Generation: ~11.80 s
* End-to-end: ~11.96 s

Interpretation: reranking adds ~0.10s but meaningfully improves top-1 relevance; generation dominates runtime.

####**Risks and Limitations**
1. **Source quality risk (StackOverflow is noisy)**
    * Some answers may be outdated, wrong, or incomplete. RAG can retrieve “popular” answers that aren’t necessarily best practice today.
2. **Evaluation limitation**
    * Hit@k is a strong retrieval metric, but it doesn’t guarantee the generated answer is correct—only that relevant sources are retrieved.
3. **Refusal/coverage tradeoff**
    * Refusal behavior is intentional and beneficial for safety, but in some products it may be seen as “didn’t answer.”
    * Tuning ```min_score``` changes this tradeoff.
4. **Latency**
    * ~12s end-to-end is fine for a notebook demo, but would need optimization for real-time product use.
5. **Citation attachment is heuristic**
    * Deterministic citation linking uses token overlap; it’s highly practical, but not a perfect semantic alignment method.

####**Final takeaway**

This notebook demonstrates a complete, modern RAG system with real-world guardrails and evaluations: reranking improves top-1 retrieval substantially, citations are enforced reliably, and refusal behavior prevents low-evidence responses. The system is technically strong for a portfolio project, with clear next steps for production hardening (speed, caching, and human-judged quality evaluation).